---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.11.2020 19:47
---

TIMER_PERIOD2 = 0.03125
function AngleBetweenXY(xa, ya, xb, yb)
    return math.atan(yb - ya, xb - xa)
end
function MoveX(x, distance, angle)
    return x + distance * math.cos(angle * bj_DEGTORAD)
end

function MoveY(y, distance, angle)
    return y + distance * math.sin(angle * bj_DEGTORAD)
end
function MoveXY(x,y, distance, angle)
    return x + distance * math.cos(angle * bj_DEGTORAD),y + distance * math.sin(angle * bj_DEGTORAD)
end
function GetUnitXY(unit)
    return GetUnitX(unit),GetUnitY(unit)
end

function AddQuest(hero, qx, qy,message)
    local x, y = GetUnitX(hero), GetUnitY(hero)
    local model = "AneuCaster"
    local player = GetOwningPlayer(hero)
    local isEnd = false
    if GetLocalPlayer() ~= player then
        model = ""
    else
        --print("звук созданного квеста")
        StartSound(bj_questSecretSound)
    end
    --local QuestPointer = AddSpecialEffect(model, x, y)
    --BlzSetSpecialEffectPitch(QuestPointer, math.rad(-90))--/bj_DEGTORAD
    print(message)
    TimerStart(CreateTimer(), 0.5, false, function()
        CreateForUnitWayToPoint(hero,qx, qy)

    end)
    TimerStart(CreateTimer(), TIMER_PERIOD2, true, function()
        local z = BlzGetLocalUnitZ(hero)
        local xc, yc = GetUnitX(hero), GetUnitY(hero)
        local angle = AngleBetweenXY(xc, yc, qx, qy)
        --BlzSetSpecialEffectPosition(QuestPointer, MoveX(xc, 130, angle / bj_DEGTORAD), MoveY(yc, 130, angle / bj_DEGTORAD), z + 10)
        --BlzSetSpecialEffectYaw(QuestPointer, angle)

        if IsUnitInRangeXY(hero, qx, qy, 200) then
            isEnd = true
        end

        if isEnd then
            if GetLocalPlayer() == player then
                StartSound(bj_questCompletedSound)
            end
            DestroyTimer(GetExpiredTimer())
            --DestroyEffect(QuestPointer)
           -- print("квест №" .. "1" .. " выполнен, даём награду")
        end
    end)
    TimerStart(CreateTimer(), 10, true, function()
        if isEnd then
            DestroyTimer(GetExpiredTimer())
            --print("Выключаем мигалку")
        else
            PingMinimapForPlayer(player, qx, qy, 3)
        end
    end)
end

--lastX=0
function CreateForUnitWayToPoint(hero,xEnd,yEnd)
    local dummy=CreateUnit(GetOwningPlayer(hero),FourCC("ewsp"),GetUnitX(hero),GetUnitY(hero),AngleBetweenXY(GetUnitX(hero),GetUnitY(hero),xEnd,yEnd)/bj_DEGTORAD)
    if UnitAddAbility(dummy,FourCC("Aloc")) then
        --print("добавлено")
    else
       -- print("Нет")
    end
    SetUnitMoveSpeed(dummy,1000)
    IssuePointOrder(dummy,"move",xEnd,yEnd)
    local i=1
    local sec=0
    local eff={}
    local p=0.1
    local lastX=GetUnitX(hero)
    local stay=false
    TimerStart(CreateTimer(), p, true, function()
        local x,y=GetUnitXY(dummy)
        local angle=GetUnitFacing(dummy)
        sec=sec+p
        if not IsUnitHidden(dummy) and not IsUnitInRangeXY(dummy,xEnd,yEnd,30) then
            eff[i]=AddSpecialEffect("AneuCaster",x,y)  --"Abilities\\Spells\\Items\\AIco\\CrownOfCmndTarget.mdl"
            -- local angle=AngleBetweenXY(x,y,point[i-1].x,point[i-1].y)/bj_DEGTORAD
            BlzSetSpecialEffectYaw(eff[i], math.rad(angle))
            BlzSetSpecialEffectPitch(eff[i], math.rad(-90))
            --print("eff "..i)
            i=i+1
            if i==4 then
                ShowUnit(dummy,false)
                ShowUnit(dummy,true)
            end
        end
        if IsUnitInRangeXY(dummy,xEnd,yEnd,200) then
            --DestroyTimer(GetExpiredTimer())
            --KillUnit(dummy)
            --print("Дамми дошёл до точки на скорости "..GetUnitMoveSpeed(dummy).." за "..sec.." секунд и за "..i.." шагов")
            --for k=1,i-1 do
            --    DestroyEffect(eff[k])
            --end
        end

        for k=1,#eff do
            if IsUnitInRangeXY(hero,BlzGetLocalSpecialEffectX(eff[k]),BlzGetLocalSpecialEffectY(eff[k]),50) then
                --DestroyEffect(eff[k])
                BlzSetSpecialEffectPosition(eff[k],5000,5000,0)
            end
        end



        if lastX~=GetUnitX(hero) then
            stay=true
            --print("юнит сдвинулся "..lastX)
            --DestroyTimer(GetExpiredTimer())
            --KillUnit(dummy)
            --print("Дамми дошёл до точки на скорости "..GetUnitMoveSpeed(dummy).." за "..sec.." секунд и за "..i.." шагов")
            for k=1,#eff do
                DestroyEffect(eff[k])
            end
            eff={}
            i=1
            ShowUnit(dummy,false)

            --UnitRemoveAbility(dummy,FourCC("Aloc"))

            --BlzPauseUnitEx(dummy,true)
            --CreateForUnitWayToPoint(hero,xEnd,yEnd)
            --print("")
        end

        if lastX==GetUnitX(hero) then
            if stay then
                stay=false
                --print
                --ShowUnit(dummy,true)
                KillUnit(dummy)
                dummy=CreateUnit(GetOwningPlayer(hero),FourCC("ewsp"),GetUnitX(hero),GetUnitY(hero),AngleBetweenXY(GetUnitX(hero),GetUnitY(hero),xEnd,yEnd)/bj_DEGTORAD)
                BlzSetUnitFacingEx(dummy,GetUnitFacing(hero))
                UnitAddAbility(dummy,FourCC("Aloc"))
                SetUnitMoveSpeed(dummy,1000)

                --BlzPauseUnitEx(dummy,false)
                SetUnitPosition(dummy,MoveXY(GetUnitX(hero),GetUnitY(hero),60,GetUnitFacing(hero)))
                IssuePointOrder(dummy,"move",xEnd,yEnd)
            end
        end
        lastX=GetUnitX(hero)

        --print("записано "..GetUnitX(hero))
    end)
end