---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 31.10.2020 13:13
---
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBossZone2()
    end)
end
function InitBossZone2()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_BashZone)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartBossAI2(gg_rct_BashZone)
            DisableTrigger(this)
        end
    end)
end



BossHPBar=nil
notSplash=true
function StartBossAI2(zone)
    local boss = FindUnitOfType(FourCC('Giam'))--баш лорд
    BOSS=boss
    BossDamaged2(boss)
    BlzSetUnitMaxHP(boss,450)
    local BossFight=true
    --print("Запущен ИИ Босса")
    local bar=HealthBarAdd(boss)
    local FW = CreateFogModifierRectBJ(false, Player(0), FOG_OF_WAR_VISIBLE, zone) --Рект босс
    FogModifierStart(FW)

    local phase = 4 --стартовая фаза
    local sec = 0
    local PhaseOn = true
    local OnAttack=true
    TimerStart(CreateTimer(), 1, true, function() --каждую секунду
        local x, y = GetUnitXY(boss)
        if not UnitAlive(boss) then-- Место где босс умер
            StartSound(bj_questCompletedSound)
            DestroyTimer(GetExpiredTimer())
            phase = 0
            BlzFrameSetVisible(bar,false)
            EnumDestructablesInRect(gg_rct_bossWin,nil,function()
                KillDestructable(GetEnumDestructable())
            end)
            --print("Даём нарграду? ,босс повержен")

        else --Проверяем есть ли живые герои,
            if BossFight then
                if not IsUnitInRange(mainHero, boss, 1000) or not UnitAlive(mainHero) then
                    BossFight=false
                    phase=0
                    DestroyFogModifier(FW)
                    --print("Герой мерт или далеко ушёл, остановка фаз")
                    BlzFrameSetVisible(bar,false)
                end
            end
        end
        if BossFight then -- если идёт бой и каждую фазу
            sec = sec + 1
            if GetUnitLifePercent(boss)<=25 then

            else

            end
            if sec >= 10 then
                sec = 0
                phase = phase + 1
                PhaseOn = true
                --print("phase " .. phase)
                if phase >= 5 then
                    phase = 0
                end
            end
            --фазы
            if phase == 1 and PhaseOn then
                PhaseOn = false
                --Doodads\LordaeronSummer\Props\PeasantGrave\PeasantGrave012
                --print("моглики со склетеами в случайных местах зоны 1+ 1 за каждые 20%% потеряного хп, максимум 5")
                for i=1,4 do
                    local tl=GetRandomLocInRect(zone)
                    CreateGrave(boss,GetLocationX(tl),GetLocationY(tl))
                    RemoveLocation(tl)
                end
            end
            if phase == 2 and PhaseOn then
                PhaseOn = false
                notSplash=false
                --print("Удар молотом вокруг себя медленно")
                if not IssueTargetOrder(boss,"attack",mainHero) then
                    IssuePointOrder(boss,"attack",GetUnitXY(mainHero))
                end


                TimerStart(CreateTimer(), 2, true, function()
                    if not IssueTargetOrder(boss,"attack",mainHero) then
                        IssuePointOrder(boss,"attack",GetUnitXY(mainHero))
                    end
                    if IsUnitInRange(boss,mainHero,300) then
                        AreaSplashMark(boss)
                    end

                    if phase~=2 then
                        DestroyTimer(GetExpiredTimer())
                        notSplash=true
                    end
                end)
            end
            if phase == 3 and PhaseOn  then
                PhaseOn = false
                --print("Разбег с отталкиавнием в сторону героя")
                --local r=5
                RunSkeleton(boss)
                TimerStart(CreateTimer(), 3, true, function()
                    RunSkeleton(boss)
                    if phase~=3 then
                        DestroyTimer(GetExpiredTimer())
                    end
                end)
            end

            if phase == 4 and PhaseOn  then -- запуск волны
                PhaseOn = false
                --print("Фаза закапывания и выкапывания и тумана")
                local nx,ny=GetRectCenterX(zone),GetRectCenterY(zone)
                local fog=AddSpecialEffect("war3mapImported\\fog.mdl",nx,ny)
                BlzSetSpecialEffectScale(fog,0.15)
                local z=BlzGetLocalSpecialEffectZ(fog)
                local sec2=0
                TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
                    if sec2>2 then
                        BlzSetSpecialEffectPosition(fog,nx,ny,z-1)
                        z=BlzGetLocalSpecialEffectZ(fog)
                    end
                    --print(z)
                    sec2=sec2+TIMER_PERIOD
                    if sec2>=9 then
                        DestroyTimer(GetExpiredTimer())
                        DestroyEffect(fog)
                    end
                end)
                local tmpLoc=GetRandomLocInRect(zone)
                local woman=CreateUnit(Player(PLAYER_NEUTRAL_PASSIVE),FourCC("nvlw"),GetLocationX(tmpLoc),GetLocationY(tmpLoc),GetUnitFacing(boss))
                RemoveLocation(tmpLoc)
                RunSkeleton(boss)

                TimerStart(CreateTimer(), 2, true, function()
                    --тут нужно какое-то действие

                    if phase~=4 then
                       -- print("фаза "..phase.." завершена")
                        DestroyTimer(GetExpiredTimer())
                        --BlzPauseUnitEx(boss,false)
                    end
                end)
            end
        else-- перезапуск боссфайта
            if IsUnitInRange(mainHero, boss, 1000) then
                --print("перезапуск боссфайта")
                IssuePointOrder(boss,"boss",GetRectCenterX(zone),GetRectCenterY(zone))
                BlzFrameSetVisible(bar,true)
                HealUnit(boss,150)
                BossFight=true
            end
        end--конец
    end)
end





function BossDamaged2(boss)
    local DamageTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        --TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
        TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
    end
    local bossTakenDamage=0
    local bossGivenDamage=0
    TriggerAddAction(DamageTrigger, function()
        local damage     = GetEventDamage() -- число урона
        if damage < 1 then return end
        local eventId         = GetHandleId(GetTriggerEventId())
        --local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
        local isEventDamaged = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)
        local target          = GetTriggerUnit() -- тот кто получил урон
        local caster          = GetEventDamageSource() -- тот кто нанёс урон


        if isEventDamaged then
            if target==boss then--  босс получает 100 урона
                bossTakenDamage=bossTakenDamage+damage
                if bossTakenDamage>=100 then
                    bossTakenDamage=0
                    --local angle=AngleBetweenXY(GetUnitX(boss),GetUnitY(boss),GetUnitXY(mainHero))/bj_DEGTORAD
                    SpireCast(boss,GetUnitXY(mainHero))
                end
            end
            if caster==boss then -- боссатакует
                bossGivenDamage=bossGivenDamage+damage
                if bossGivenDamage>=100 then
                    bossGivenDamage=0
                    --local r=GetRandomInt(1,5)

                    --if r==1 and IsUnitInRange(boss,mainHero,300) then
                    if notSplash then
                        AreaSplashMark(boss)
                    end
                    --end
                end
            end
        end

    end)
end

function CreateGrave(boss,x,y)
    local r=GetRandomInt(0,2)
    DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.mdl",x,y))
    local eff=AddSpecialEffect("Doodads\\LordaeronSummer\\Props\\PeasantGrave\\PeasantGrave"..r,x,y)
    --war3mapImported\fog.mdl
    local sec=0
    local z=BlzGetLocalSpecialEffectZ(eff)
    BlzSetSpecialEffectScale(eff,2.3)
    BlzSetSpecialEffectYaw(eff, math.rad(GetRandomInt(0,360)))
    --print(z.." стартовая")
    local skeleton=nil
    local id={FourCC("uske"),FourCC("u004"),FourCC("u006"),FourCC("u007"),FourCC("nvlw"),FourCC("u009"),FourCC("u000")}
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        if sec>2 then
            BlzSetSpecialEffectPosition(eff,x,y,z-1)
            z=BlzGetLocalSpecialEffectZ(eff)
        end
        --print(z)
        sec=sec+TIMER_PERIOD
        if sec>=4.5 then
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(eff)
            DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.mdl",x,y))
            if GetUnitTypeId(boss)==FourCC("u00B") then
                skeleton=CreateUnit(GetOwningPlayer(boss),id[GetRandomInt(1,#id)],x,y,GetRandomInt(0,360))
            else
                skeleton=CreateUnit(GetOwningPlayer(boss),FourCC("uske"),x,y,GetRandomInt(0,360))
            end
            if GetUnitTypeId(skeleton)==FourCC("nvlw") then --девочка
                SetUnitOwner(skeleton,Player(PLAYER_NEUTRAL_PASSIVE),true)
            end

            if GetUnitTypeId(skeleton)==FourCC("u000") then --красный босс
                StunUnit(boss,0.2)
                --print("Редбосс")
                TimerStart(CreateTimer(), 5, true, function()
                    if IsUnitInRange(boss,mainHero,500) and StunSystem[GetHandleId(boss)].Time==0 and UnitAlive(boss) then
                        CreateMeteorMark(boss,GetUnitXY(mainHero))
                    end
                    if not UnitAlive(boss) then
                        DestroyTimer(GetExpiredTimer())
                    end
                end)
            end


            UnitApplyTimedLife(skeleton,FourCC('BTLF'),25)
            if not IssueTargetOrder(skeleton,"attack",mainHero) then
                IssuePointOrder(skeleton,"attack",GetUnitXY(mainHero))
            end
        end
    end)
    return skeleton
end

function RunSkeleton(boss)
    BlzPauseUnitEx(boss,true)
    --SetUnitAnimation(boss,"walk")
    SetUnitAnimationByIndex(boss,6)
    --print(r)
    --r=r+1
    SetUnitTimeScale(boss,3)
    local angle=AngleBetweenXY(GetUnitX(boss),GetUnitY(boss),GetUnitXY(mainHero))/bj_DEGTORAD
    SetUnitFacing(boss,angle)
    UnitAddForceSimple(boss,angle,10,500,6)
end
function AreaSplashMark(boss)
    BlzPauseUnitEx(boss,true)
    SetUnitAnimation(boss,"attack")
    SetUnitTimeScale(boss,0.5)
    local nx,ny=MoveXY(GetUnitX(boss),GetUnitY(boss),200,GetUnitFacing(boss))
    local mark=AddSpecialEffect("Snipe Target",nx,ny)
    BlzSetSpecialEffectScale(mark,10)
    TimerStart(CreateTimer(), 1.2, false, function()
        BlzPauseUnitEx(boss,false)
        DestroyEffect(mark)
        BlzSetSpecialEffectPosition(mark,5000,5000,0)
        --nx,ny=MoveXY(GetUnitX(boss),GetUnitY(boss),200,GetUnitFacing(boss))
        DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic",nx,ny))
        UnitDamageArea(boss,100,nx,ny,200) --урон
        StunArea(boss,200,1,nx,ny)
        SetUnitTimeScale(boss,1)
        ResetUnitAnimation(boss)
    end)
end
