---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.11.2020 20:48
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBossZoneWE()
    end)
end
function InitBossZoneWE()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_WEbolldBoss)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartBossAIWE(gg_rct_WEbolldBoss)
            DisableTrigger(this)
        end
    end)
end


function StartBossAIWE(zone)
    local boss=FindUnitOfType(FourCC("hwt3"))
    --print("запущен ии водного элементаля, он должен что то делать")
    TimerStart(CreateTimer(), 5, true, function()
        if IsUnitInRange(boss,mainHero,500) and not IsUnitPaused(boss) then
            UnitAddAbility(boss,FourCC("AInv"))
            UnitAddItemById(boss,FourCC("I004"))
            ShowUnit(boss,false)
            UnitAddForceSimple(boss,GetUnitFacing(boss),15,600,5)
        end
        if not UnitAlive(boss) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end