---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.11.2020 20:48
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBossZoneWE()
    end)
end
function InitBossZoneWE()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_WEbolldBoss)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartBossAIWE(gg_rct_WEbolldBoss)
            ClearMapMusicBJ()
            PlayMusicBJ(gg_snd_Hollow_Knight_OST___Nosk__Boss_Theme_u)
            DisableTrigger(this)
            udg_RevivePoint = gg_rct_RedKeyDoor
        end
    end)
end


function StartBossAIWE(zone)
    local boss=FindUnitOfType(FourCC("hwt3"),1000,GetRectCenterX(zone),GetRectCenterY(zone))
    local hero=boss
    StunUnit(boss,0.2)
    UnitAddType(boss,UNIT_TYPE_UNDEAD)
    --print("запущен ии водного элементаля, он должен что то делать")
    TimerStart(CreateTimer(), 5, true, function()
        if IsUnitInRange(boss,mainHero,500) and StunSystem[GetHandleId(boss)].Time==0 and UnitAlive(boss)  then
            UnitAddAbility(boss,FourCC("AInv"))
            UnitAddItemById(boss,FourCC("I004"))
            ShowUnit(boss,false)
            UnitAddForceSimple(boss,GetUnitFacing(boss),15,600,5)
            local bar=AddSpecialEffect("Progressbar",GetUnitXY(hero))
            BlzSetSpecialEffectColor(bar,255,255,255)
            BlzPlaySpecialEffect(bar,ANIM_TYPE_BIRTH)
            BlzSetSpecialEffectTimeScale(bar,0.22)
            BlzSetSpecialEffectScale(bar,1.5)
            local sec=0
            TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
                sec=sec+TIMER_PERIOD
                BlzSetSpecialEffectPosition(bar,GetUnitX(hero),GetUnitY(hero),BlzGetLocalUnitZ(hero)+260)
                if sec>5 then
                    DestroyTimer(GetExpiredTimer())
                    DestroyEffect(bar)
                    BlzSetSpecialEffectPosition(bar,5000,5000,0)
                end
            end)
        end
        if not UnitAlive(boss) then
            DestroyTimer(GetExpiredTimer())
            --print("dead")
            ClearMapMusicBJ()
            PlayMusicBJ(gg_snd_Blood_Omen__Legacy_of_Kain___Kain_s_Mausoleum)
            CreateArrowMark(GetUnitXY(boss))
        end
    end)
end

function CreateArrowMark(x,y)
    TimerStart(CreateTimer(), 20, false, function()
        local _,k,units=FindUnitOfType(FourCC("hrif"))
        --print(k)
        if k==0 then
           -- print("могилки не найдены")
        end
        for i=1,#units do
            --print(i)
            local eff = AddSpecialEffect("AneuCaster", GetUnitXY(units[i]))  --"Abilities\\Spells\\Items\\AIco\\CrownOfCmndTarget.mdl"
            BlzSetSpecialEffectPitch(eff, math.rad(-90))
            BlzSetSpecialEffectZ(eff, BlzGetLocalUnitZ(units[i]) + 350)
            TimerStart(CreateTimer(), 0.1, true, function()
                local angle=GetUnitFacing(units[i])
                --print("поворот "..angle)
                BlzSetSpecialEffectYaw(eff, math.rad(angle))
            end)
        end
    end)
end

