---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 31.10.2020 13:13
---
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBossZone()
    end)
end
function InitBossZone()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_boss)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartBossAI(gg_rct_boss)
            DisableTrigger(this)
        end
    end)
end




function StartBossAI(zone)
    local boss = FindUnitOfType(FourCC('u005'))
    local BossFight=true
    print("Запущен ИИ Босса")

    local FW = CreateFogModifierRectBJ(false, Player(0), FOG_OF_WAR_VISIBLE, zone) --Рект босс
    FogModifierStart(FW)

    local phase = 3 --стартовая фаза
    local sec = 0
    local PhaseOn = true
    local OnAttack=true
    TimerStart(CreateTimer(), 1, true, function() --каждую секунду
        local x, y = GetUnitXY(boss)
        if not UnitAlive(boss) then-- Место где босс умер тиник
            StartSound(bj_questCompletedSound)
            DestroyTimer(GetExpiredTimer())
            phase = 0
            print("Даём нарграду? ,босс повержен")

        else --Проверяем есть ли живые герои, когда тиник жив
            if BossFight then
                if not IsUnitInRange(mainHero, boss, 1500) then
                    BossFight=false
                    phase=0
                    DestroyFogModifier(FW)
                    print("Герой мерт или далеко ушёл, остановка фаз")
                end
            end
        end
        if BossFight then -- если идёт бой
            sec = sec + 1
            if sec >= 10 then
                sec = 0
                phase = phase + 1
                PhaseOn = true
                --print("phase " .. phase)
                if phase >= 4 then
                    phase = 0
                end
            end
            --фазы
            if phase == 1 and PhaseOn then
                PhaseOn = false
                print("Призываем скелетов")
                local skeleton={}
                skeleton[1]=CreateUnit(GetOwningPlayer(boss),FourCC("uske"),GetRectMaxX(zone),GetRectMaxY(zone),GetRandomInt(0,360))
                skeleton[2]=CreateUnit(GetOwningPlayer(boss),FourCC("uske"),GetRectMaxX(zone)-GetRectWidthBJ(zone),GetRectMinY(zone)+GetRectHeightBJ(zone),GetRandomInt(0,360))
                skeleton[3]=CreateUnit(GetOwningPlayer(boss),FourCC("uske"),GetRectMinX(zone)+GetRectWidthBJ(zone),GetRectMinY(zone),GetRandomInt(0,360))
                skeleton[4]=CreateUnit(GetOwningPlayer(boss),FourCC("uske"),GetRectMinX(zone),GetRectMinY(zone),GetRandomInt(0,360))
                for i=1,#skeleton do
                    if not IssueTargetOrder(skeleton[i],"attack",mainHero) then
                        IssuePointOrder(skeleton[i],"attack",GetUnitXY(mainHero))
                    end
                end
            end
            if phase == 2 and PhaseOn then
                PhaseOn = false
                print("Падающие люстры")
                TimerStart(CreateTimer(), 1, true, function()
                    MarkAndFall(GetUnitX(mainHero),GetUnitY(mainHero),"HFMChandelier",boss) --люстра
                    if phase~=2 then
                        DestroyTimer(GetExpiredTimer())
                    end
                end)

            end
            if phase == 3 and PhaseOn  then -- оживление големов
                PhaseOn = false
                print("Пускаем волну в 1 из 3 направлений")
                local r=GetRandomInt(1,3)
                local xs,ys=GetRectCenterX(zone),GetRectCenterY(zone)
                if r==1 then
                    xs=xs-GetRectWidthBJ(zone)/3
                elseif r==2 then
                    xs=xs+GetRectWidthBJ(zone)/3
                end
                local eff=AddSpecialEffect("s_cube1",xs,ys)
                BlzSetSpecialEffectZ(eff,GetUnitZ(mainHero)-45)
                BlzSetSpecialEffectMatrixScale(eff,4,14,0.5)
                BlzSetSpecialEffectColor(eff,255,0,0)
                BlzSetSpecialEffectAlpha(eff,100)

                TimerStart(CreateTimer(), 3, false, function()
                    CreateFirePillar(xs,ys,boss,zone)
                    DestroyEffect(eff)
                    BlzSetSpecialEffectPosition(eff,5000,5000,0)
                    DestroyTimer(GetExpiredTimer())
                end)
            end
        else-- перезапуск боссфайта
            if IsUnitInRange(mainHero, boss, 1000) then
                print("перезапуск боссфайта")
                HealUnit(boss,9999)
                BossFight=true
            end
        end--конец
    end)
end

function MarkAndFall(x,y,effModel,hero)
    local mark=AddSpecialEffect("Snipe Target",x,y)
    BlzSetSpecialEffectScale(mark,5)
    TimerStart(CreateTimer(), 2, false, function()

        local FallenEff=AddSpecialEffect(effModel,x,y)
        BlzSetSpecialEffectZ(FallenEff,1000)
        BlzSetSpecialEffectYaw(FallenEff, math.rad(GetRandomReal(0,360)))
        TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
            local z=BlzGetLocalSpecialEffectZ(FallenEff)
            BlzSetSpecialEffectZ(FallenEff,z-25)
            if z<=GetTerrainZ(x,y) then
                DestroyEffect(mark)
                BlzSetSpecialEffectPosition(mark,5000,5000,0)
                DestroyTimer(GetExpiredTimer())
                DestroyEffect(FallenEff)
                BlzSetSpecialEffectPosition(FallenEff,5000,5000,0)
                DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster",x,y))
                UnitDamageArea(hero,50,x,y,150) --при падении камня
                UnitDamageArea(mainHero,50,x,y,150)
            end
        end)
    end)
end

function CreateFirePillar(xs,ys,boss,zone)
    ys=ys+700
    local step=100
    xs=xs-step*1.7
    local x=xs
    for k=1,14 do
        for i =1,3 do
            x=x+step
            local eff=AddSpecialEffect("Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl",x,ys-step*(k-1))
            UnitDamageArea(boss,99,x,ys-step*(k-1),step*2)
        end
        x=xs
    end

end