---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.11.2020 20:48
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitGreenBoss()
    end)
end
function InitGreenBoss()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_GreenBoss)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartGreenRed(gg_rct_GreenBoss)
            DisableTrigger(this)
        end
    end)
end


function StartGreenRed(zone)
    local boss=FindUnitOfType(FourCC("u002"),1000,GetRectCenterX(zone),GetRectCenterY(zone))
    BOSS=boss
    UnitAddAbility(boss,FourCC("A00B"))
    local spawn=true
    StunUnit(boss,0.2)
    --print("Гринбосс")
    TimerStart(CreateTimer(), 1, true, function()
        if StunSystem[GetHandleId(boss)].Time==0 then
            if IsUnitInRange(boss,mainHero,1600)  then
                if spawn then
                    --local nx,ny=0,0
                    local angle=45
                    for i=1,8 do
                        local nx,ny=MoveXY(GetUnitX(boss),GetUnitY(boss),150,angle*i)
                        CreateUnit(GetOwningPlayer(boss),FourCC("osp1"),nx,ny,0)
                       -- print(i.." вардов")
                    end
                end
                spawn=false
                IssuePointOrder(boss,"ward",GetUnitXY(mainHero))
                --print("ward")
                --osp1
            else
                spawn=true
            end
        end
        if not UnitAlive(boss) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end
