---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.11.2020 20:48
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitIceBoss()
    end)
end
function InitIceBoss()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_IceBoss)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartIceBoss(gg_rct_IceBoss)
            DisableTrigger(this)
        end
    end)
end


function StartIceBoss(zone)
    local boss=FindUnitOfType(FourCC("u001"))
    UnitAddAbility(boss,FourCC("A00C"))
    --print("Ледяной босс")
    TimerStart(CreateTimer(), 1, true, function()
        if  not IsUnitPaused(boss) then
            if  OrderId2String(GetUnitCurrentOrder(boss))~="blizzard" then
                IssuePointOrder(boss,"blizzard",GetUnitXY(boss))
            end
        end
        if not UnitAlive(boss) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end
