---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.11.2020 20:48
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitLBoss()
    end)
end
function InitLBoss()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_LightFight)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if hero==mainHero then
            StartBossL(gg_rct_LightFight)
            DisableTrigger(this)
        end
    end)
end


function StartBossL(zone)
    local boss=FindUnitOfType(FourCC("u00D"),1000,GetRectCenterX(zone),GetRectCenterY(zone))
    BOSS=boss
    UnitAddType(boss,UNIT_TYPE_UNDEAD)
    StunUnit(boss,0.2)
    --print("Редбосс")
    TimerStart(CreateTimer(), 5, true, function()
        if IsUnitInRange(boss,mainHero,500) and StunSystem[GetHandleId(boss)].Time==0 and UnitAlive(boss) then
            if UnitAlive(boss) then
                --print("хочет хильнуть")
                CreateHealWMark(boss)
            end
        end
        if not UnitAlive(boss) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

--Abilities\Spells\Human\HolyBolt\HolyBoltSpecialArt.mdl
--Abilities\Spells\Human\Resurrect\ResurrectTarget.mdl

function CreateHealWMark(boss)
    local e=nil
    local x,y=GetUnitXY(boss)
    local hp={}
    local units={}
    GroupEnumUnitsInRange(perebor,x,y,1000,nil)
    while true do
        e = FirstOfGroup(perebor)

        if e == nil then break end
        if UnitAlive(e) and IsUnitAlly(e,GetOwningPlayer(boss)) then
            table.insert(hp,GetUnitLifePercent(e))
            table.insert(units,e)
        end
        GroupRemoveUnit(perebor,e)
    end

    local key,min = 1,hp[1]--, t[1]
    for k, v in ipairs(hp) do
        if hp[k] < min then
            key, min = k, v
        end
    end

    --print(key, min)
    local mark=AddSpecialEffect("Alarm",GetUnitXY(units[key]))
    BlzSetSpecialEffectScale(mark,1)
    local sec=2
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        BlzSetSpecialEffectPosition(mark,GetUnitX(units[key]),GetUnitY(units[key]),BlzGetUnitZ(units[key])+30)
        sec=sec-TIMER_PERIOD
        if sec<=0 then
            DestroyTimer(GetExpiredTimer())
            if StunSystem[GetHandleId(boss)].Time==0 and UnitAlive(boss) and UnitAlive(units[key]) then
                HealUnit(units[key],100,nil,"Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt")
            end
            BlzSetSpecialEffectPosition(mark,5000,5000,0)
            local is,hero=UnitDamageArea(boss,100,GetUnitX(units[key]),GetUnitY(units[key]),150)
            if is then
                DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt",GetUnitXY(hero)))
            end
        end
    end)

end

