---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.11.2020 23:27
---
--"u00B
do
    TimerStart(CreateTimer(), 1, false, function()
        RegisterNecroBoss()
    end)
end


function RegisterNecroBoss()
    local gg_trg_RANGE = CreateTrigger()
    local boss,k=FindUnitOfType(FourCC("u00B"))
    --print(k)
    TriggerRegisterUnitInRangeSimple(gg_trg_RANGE, 700, boss)
    TriggerAddAction(gg_trg_RANGE, function()
        local hero=GetTriggerUnit()
        --print("Запускаем некроманта")
        TimerStart(CreateTimer(), 1, true, function()
            if IsUnitInRange(hero,boss,1000) then
                local tl=GetRandomLocInRect(gg_rct_FieldSkeletons)
                local x,y=GetLocationX(tl),GetLocationY(tl)
                CreateGrave(boss,x,y)
                RemoveLocation(tl)
            end

            if not UnitAlive(boss) then
                DestroyTimer(GetExpiredTimer())
            end
        end)
        DisableTrigger(GetTriggeringTrigger())
    end)
end