---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.11.2020 23:27
---
--"u00B
do
    TimerStart(CreateTimer(), 0.2, false, function()
        RegisterPeonBoss()
    end)
end


function RegisterPeonBoss()
    --[[local gg_trg_RANGE = CreateTrigger()
    local boss,k=FindUnitOfType(FourCC("o002"))
    BOSS=boss
    --print(k)
    TriggerRegisterUnitInRangeSimple(gg_trg_RANGE, 1000, boss)
    TriggerAddAction(gg_trg_RANGE, function()
        local hero=GetTriggerUnit()
        --print("Запускаем некроманта")
        if hero==mainHero then
            --print(GetUnitName())
            DisableTrigger(GetTriggeringTrigger())
            --StartPEONAI(boss)
        end

    end)]]
    --print("регистрация пеона")
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_PeonPlace)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartPEONAI()
            DisableTrigger(this)
        end
    end)


end

bsx,bsy=0,0
PeonIsRed=false
function StartPEONAI()
    local boss,err = FindUnitOfType(FourCC('o002'))
    BOSS=boss
    UnitRemoveAbility(boss,FourCC("Avul"))
    --print("запускаем ИИ пеона")
    if err==0 then
        print('Пеон не найден, обратитесь к автору карты')
    end
    bsx,bsy=GetUnitXY(boss)
    --BossDamaged(boss)
    local BossFight=true
    UnitAddAbility(boss,FourCC("A008"))
    --UnitAddAbility(boss,FourCC("Avul"))
    UnitAddType(boss,UNIT_TYPE_UNDEAD)
    --print("Запущен ИИ Босса пеона")
    local bar=HealthBarAdd(boss)
    --local FW = CreateFogModifierRectBJ(false, Player(0), FOG_OF_WAR_VISIBLE, zone) --Рект босс
    --FogModifierStart(FW)

    local phase = 5 --стартовая фаза
    local sec = 0
    local PhaseOn = true
    local OnAttack=true
    TimerStart(CreateTimer(), 1, true, function() --каждую секунду
        local x, y = GetUnitXY(boss)
        if not UnitAlive(boss) then-- Место где босс умер
            DestroyTimer(GetExpiredTimer())
            phase = 0
            BlzFrameSetVisible(bar,false)
            print("Bergios's boss is defeated, victory in 10 seconds")
            TimerStart(CreateTimer(), 10, false, function()
                CustomVictoryBJ(Player(0),true,true)
            end)

        else --Проверяем есть ли живые герои, когда тиник жив
            if BossFight then
                if not IsUnitInRange(mainHero, boss, 2000) or not UnitAlive(mainHero) then
                    BossFight=false
                    phase=0
                    --DestroyFogModifier(FW)
                    --print("Герой мерт или далеко ушёл, остановка фаз")
                    BlzFrameSetVisible(bar,false)
                end
            end
        end
        if BossFight then -- если идёт бой и каждую фазу
            sec = sec + 1
            if GetUnitLifePercent(boss)<=50 and not PeonIsRed then
                boss=ReplaceUnitBJ(boss,FourCC("o005"),1) --0 3
                UnitAddAbility(boss,FourCC("A008"))
                UnitAddType(boss,UNIT_TYPE_UNDEAD)
                BlzFrameSetVisible(bar,false)
                bar=HealthBarAdd(boss)
                PeonIsRed=true
                --print("peon is red")

            end
            if sec >= 10 then
                sec = 0
                phase = phase + 1
                PhaseOn = true
                --print("phase " .. phase)
                if phase >= 5 then --число фаз +1
                    phase = 0
                end
            end
            --фазы
            if phase == 1 and PhaseOn then
                SetUnitPositionSmooth(boss,bsx,bsy)
                PhaseOn = false
                --print("Серия я ударов")
                -- Удар в центр
                PeonAttackCenter(boss)


                TimerStart(CreateTimer(), 4, false, function()
                    PeonAttackLeft(boss)
                end)

                TimerStart(CreateTimer(), 7, false, function()
                    PeonAttackRight(boss,280)
                end)
                    -- Удары справа налево
                -- Замах слева на право
            end
            if phase == 2 and PhaseOn then
                SetUnitPositionSmooth(boss,bsx,bsy)
                UnitRemoveAbility(boss,FourCC("Avul"))
                PhaseOn = false
                local nx,ny=MoveXY(x,y,-1000,GetUnitFacing(boss))

                CameraSetEQNoiseForPlayer(Player(0), 3)

                --print("Призыв катапульт, стреляют навесом")
                TimerStart(CreateTimer(), 2, false, function()
                    IssuePointOrder(boss,"move",nx,ny)
                    CameraClearNoiseForPlayer(Player(0))
                    local e=nil
                    local id=FourCC("ocat")
                    GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
                        while true do
                            e = FirstOfGroup(perebor)

                            if e == nil then break end
                            if UnitAlive(e) and GetUnitTypeId(e)==id then
                                SetUnitOwner(e,Player(PLAYER_NEUTRAL_PASSIVE),true)
                                AttackWMark(e)

                                RepeatAG(e)

                            end
                            GroupRemoveUnit(perebor,e)
                        end
                    TimerStart(CreateTimer(), 8, false, function()
                        GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
                        while true do
                            e = FirstOfGroup(perebor)

                            if e == nil then break end
                            if UnitAlive(e) and GetUnitTypeId(e)==id then
                                SetUnitOwner(e,Player(PLAYER_NEUTRAL_PASSIVE),true)
                                IssueImmediateOrder(e,"stop")
                                --IssuePointOrder(boss,"move",x,y)
                                SetUnitZ(boss,0)
                            end
                            GroupRemoveUnit(perebor,e)
                        end


                    end)

                end)

            end
            if phase == 3 and PhaseOn  then -- запуск волны
                SetUnitPositionSmooth(boss,bsx,bsy)
                PhaseOn = false
                --CameraSetEQNoiseForPlayer(Player(0), 4)
                --TriggerSleepAction(2.00)
                --CameraClearNoiseForPlayer(Player(0))

                --print("Пеон убегает, а потом прыгает на героя")
                PeonJumpAndFall(boss)
            end

            if (phase == 4 or phase == 0)  and PhaseOn  then -- запуск волны
                SetUnitPositionSmooth(boss,bsx,bsy)
                PhaseOn = false
                -- gg_rct_PeonPlace
                for i=1,5 do
                    local nx,ny=GetLocationX(GetRandomLocInRect(gg_rct_PeonPlace)),GetLocationY(GetRandomLocInRect(gg_rct_PeonPlace))
                    local peon=CreateUnit(Player(PLAYER_NEUTRAL_AGGRESSIVE),FourCC("o004"),nx,ny,GetRandomInt(0,360))
                    IssueTargetOrder(peon,"attack",mainHero)
                    --print("peon")
                end

                TimerStart(CreateTimer(), 4, false, function()
                    PeonAttackRight(boss,300)
                end)
                --print("Серия атак создающая шипы")

            end

            if phase == 5 and PhaseOn  then -- запуск волны
                PhaseOn = false
                --print("раскалывающий удар")
                --PeonAttackCenter(boss)
                Wall2Line(boss)

            end
        else-- перезапуск боссфайта
            if IsUnitInRange(mainHero, boss, 1000) then
                --print("перезапуск боссфайта")
                --IssuePointOrder(boss,"move",GetRectCenterX(zone),GetRectCenterY(zone))
                BlzFrameSetVisible(bar,true)
                --HealUnit(boss,500)
                BossFight=true
            end
        end--конец
    end)
end

function PeonAttackCenter(boss)
    --print("Запомни этот поворот "..GetUnitFacing(boss))
    SetUnitFacing(boss,278)
    local x,y=GetUnitXY(boss)
    x,y=MoveXY(x,y,500,GetUnitFacing(boss))
    local mark=AddSpecialEffect("Alarm",x,y)
    BlzSetSpecialEffectScale(mark,3)
    SetUnitAnimationByIndex(boss,2)
    TimerStart(CreateTimer(), 1, false, function()--первая задержка
        local k=0
        TimerStart(CreateTimer(), 0.5, true, function()
            DestroyEffect(mark)
            SetUnitAnimationByIndex(boss,2)
            BlzSetSpecialEffectPosition(mark,5000,5000,0)
            DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic",x,y))
            UnitDamageArea(boss,100,x,y,300)

            k=k+1
            if k>4 then
                DestroyTimer(GetExpiredTimer())
                ResetUnitAnimation(boss)
            end
        end)
    end)
end

function PeonAttackLeft(boss)
    BlzSetUnitFacingEx(boss,295)
    local x,y=GetUnitXY(boss)
    --x,y=MoveXY(x,y,500,GetUnitFacing(boss))
    local mark=AddSpecialEffect("Alarm",x,y)
    BlzSetSpecialEffectScale(mark,2)
    SetUnitAnimationByIndex(boss,2)
    local k=0
    TimerStart(CreateTimer(), 0.35, true, function()
        DestroyEffect(mark)
        SetUnitFacing(boss,GetUnitFacing(boss)-10)
        local nx,ny=MoveXY(x,y,500,GetUnitFacing(boss))
        SetUnitAnimationByIndex(boss,3)
        --BlzSetSpecialEffectPosition(mark,5000,5000,0)
        DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic",nx,ny))
        UnitDamageArea(boss,100,nx,ny,200)

        k=k+1
        if k>7 then
            DestroyTimer(GetExpiredTimer())
            ResetUnitAnimation(boss)
        end
    end)
end

function PeonAttackRight(boss,range)
    BlzSetUnitFacingEx(boss,278)
    local x,y=GetUnitXY(boss)
    --  x,y=MoveXY(x,y,500,GetUnitFacing(boss))
    --local mark=AddSpecialEffect("Alarm",x,y)
    BlzSetSpecialEffectScale(mark,2)
    SetUnitAnimationByIndex(boss,13)
    if not range then range=500 end

    TimerStart(CreateTimer(), 2.5, false, function()
        local k=0
        local angle=230
        TimerStart(CreateTimer(), 0.1, true, function()
           -- print("Проводим топором "..k)
            local nx,ny=MoveXY(x,y,range,angle)
            angle=angle+17
            --print(angle)
            DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic",nx,ny))
            UnitDamageArea(boss,100,nx,ny,200)
            k=k+1
            if k>7 then
                DestroyTimer(GetExpiredTimer())
                ResetUnitAnimation(boss)
            end
        end)
    end)
end

function AttackWMark(e)
    local x,y=GetUnitXY(mainHero)
    local nx,ny=MoveXY(x,y,GetRandomInt(0,500),GetRandomInt(0,360))
    if not IssuePointOrderById(e,851984,nx,ny) then
       -- print("каммон, такого приказа нет")
        IssuePointOrderById(e,851984,nx,ny)
    end
    --print(GetUnitCurrentOrder(e))
    local mark=AddSpecialEffect("Alarm",nx,ny)
    BlzSetSpecialEffectZ(mark,BlzGetLocalSpecialEffectZ(mark)+50)
    TimerStart(CreateTimer(), 0.9, false, function()
        --print(GetUnitCurrentOrder(e))
       IssueImmediateOrder(e,"stop")
    end)
    BlzSetSpecialEffectScale(mark,1)
    TimerStart(CreateTimer(), 2.5, false, function()
        if PeonIsRed then
            local eff=AddSpecialEffect("Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl",nx,ny)
            UnitDamageArea(e,99,nx,ny,150)
        end
        DestroyEffect(mark)
        BlzSetSpecialEffectPosition(mark,5000,5000,0)
    end)
end

function RepeatAG(e)
    local k=0
    TimerStart(CreateTimer(), 3, true, function()
        AttackWMark(e)
        --print("Повтор таймер периода атаки катапульт ".. GetUnitName(e))
        k=k+1
        if k>3 then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function PeonJumpAndFall(boss)
    SetUnitAnimation(boss,"death")
    local sx,sy=GetUnitXY(boss)
    local up=true
    local down=true
    local z=0
    local h=4000
    TimerStart(CreateTimer(), 2.1, false, function()
        SetUnitTimeScale(boss,0)
        local mark=AddSpecialEffect("Alarm",0,0)
        local zMark=550
        local dx,dy=0,0
        BlzSetSpecialEffectScale(mark,4)
        TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
           -- BlzSetSpecialEffectPosition(mark,GetUnitX(mainHero),GetUnitY(mainHero),zMark)

            if GetUnitZ(boss)<=h and up then
                SetUnitZ(boss,GetUnitZ(boss)+60)
            else
                if down then
                    --print("Пора опускаться "..GetUnitZ(boss))
                    up=false
                    z=GetUnitZ(boss)
                    down=false
                end
            end

            if not up then
                if z>=0 then
                    if z>1000 then
                        local bx,by=MoveXY(GetUnitX(mainHero),GetUnitY(mainHero),400,GetUnitFacing(boss)-180)
                        SetUnitPosition(boss,bx,by)
                        BlzSetSpecialEffectPosition(mark,GetUnitX(mainHero),GetUnitY(mainHero),zMark)
                        dx,dy=bx,by
                    else
                        if mark then

                        end
                    end
                    if z>=500 then
                        --print("опускаем юнита "..GetUnitZ(boss))
                        SetUnitZ(boss,GetUnitZ(boss)-30)

                    end
                    z=z-30
                end
                if z<=495 then
                   -- print("опустился")
                    CameraSetEQNoiseForPlayer(Player(0), 3)
                    local bx,by=MoveXY(GetUnitX(boss),GetUnitY(boss),400,GetUnitFacing(boss)-180)
                    DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic",bx,by))
                    UnitDamageArea(boss,100,dx,dy,500)
                    DestroyTimer(GetExpiredTimer())
                    DestroyEffect(mark)
                    BlzSetSpecialEffectPosition(mark,5000,5000,0)



                    TimerStart(CreateTimer(), 5, false, function()
                        CameraClearNoiseForPlayer(Player(0))
                        SetUnitTimeScale(boss,1)
                        ResetUnitAnimation(boss)
                        SetUnitPosition(boss,sx,sy)
                    end)
                end
            end

        end)
    end)
end

function Wall2Line(boss)
    local sec=10
    local k=1-GetUnitLifePercent(boss)/100
    local p=0.1
    --print(k)
    local x,y=GetUnitXY(boss)
    local angle=AngleBetweenXY(x,y,GetUnitXY(mainHero))/bj_DEGTORAD
    TimerStart(CreateTimer(),p,true, function()

        --angle=GetUnitFacing(boss)

        x,y=MoveXY(x,y,80,angle)
        CreateWallElement(x,y,10,boss)
        sec=sec-p
        if sec<=0 then
            DestroyTimer(GetExpiredTimer())

        end
    end)
end