---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.11.2020 20:48
---

do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBossRed()
    end)
end
function InitBossRed()
    local this = CreateTrigger()
    TriggerRegisterEnterRectSimple(this, gg_rct_RedBossKey)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if IsUnitType(hero,UNIT_TYPE_HERO) then
            StartBossRed(gg_rct_RedBossKey)
            DisableTrigger(this)
        end
    end)
end


function StartBossRed(zone)
    local boss=FindUnitOfType(FourCC("u000"),1000,GetRectCenterX(zone),GetRectCenterY(zone))
    --print("Редбосс")
    TimerStart(CreateTimer(), 5, true, function()
        if IsUnitInRange(boss,mainHero,500) and not IsUnitPaused(boss) then
            CreateMeteorMark(boss,GetUnitXY(mainHero))
        end
        if not UnitAlive(boss) then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function CreateMeteorMark(boss,x,y)
    local mark=AddSpecialEffect("Snipe Target",x,y)
    BlzSetSpecialEffectScale(mark,5)
    TimerStart(CreateTimer(), 2, false, function()
        DestroyEffect(mark)
        BlzSetSpecialEffectPosition(mark,5000,5000,0)
        local eff=AddSpecialEffect("Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireTarget.mdl",x,y)
        TimerStart(CreateTimer(), 1, false, function()
            --print("Упал?")
            UnitDamageArea(boss,50,x,y,150)
        end)
    end)
    --"Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireTarget.mdl"
end
