---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBB()
    end)
end

function InitBB()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if not HERO[0].isShield then
            if GetSpellAbilityId() == FourCC('dssd') then --мыши
                local caster=GetTriggerUnit()
                UnitMakeAbilityPermanent(caster,true,FourCC('dssd')) --сами мыши
                UnitMakeAbilityPermanent(caster,true,FourCC('A002')) --Пожирание
                UnitMakeAbilityPermanent(caster,true,FourCC('A005')) -- контроль разума
                UnitMakeAbilityPermanent(caster,true,FourCC('A007')) -- копьё
                UnitMakeAbilityPermanent(caster,true,FourCC('A00G')) -- молния
                UnitMakeAbilityPermanent(caster,true,FourCC('A00M')) -- армия тьмы
                local curMP=GetUnitState(caster,UNIT_STATE_MANA)
                --print(curMP)
                UnitAddItemById(mainHero,FourCC("I00A")) --превращаемся в мышей

                --local slot=RemoveAllItems(caster)
                --local maxHP=BlzGetUnitMaxHP(caster)
                --local curHP=GetUnitState(caster,UNIT_STATE_LIFE)
                TimerStart(CreateTimer(), 0.02, false, function()
                    SetUnitState(caster,UNIT_STATE_MANA,curMP)
                end)
                -- UnitAddItemById(caster,FourCC("I004"))
                TimerStart(CreateTimer(), 3, false, function()
                    --slot=RemoveAllItems(caster)
                    --maxHP=BlzGetUnitMaxHP(caster)
                    --curHP=GetUnitState(caster,UNIT_STATE_LIFE)
                    --UnitAddAbility(caster,FourCC("S001")) -- перелючение обратно
                    --AddAlItems(caster,slot,maxHP,curHP)
                    curMP=GetUnitState(caster,UNIT_STATE_MANA)
                    --print(curMP)
                    if UnitAlive(mainHero) then
                        UnitAddItemById(mainHero,FourCC("I00B")) -- превращаемся обратно
                    else
                        --print("умер в форме мышей ожидаем воскрешения")
                        TimerStart(CreateTimer(), 0.02, true, function()
                            if UnitAlive(mainHero) then
                                DestroyTimer(GetExpiredTimer())
                                curMP=GetUnitState(caster,UNIT_STATE_MANA)
                                UnitAddItemById(mainHero,FourCC("I00B"))
                                TimerStart(CreateTimer(), 0.02, false, function()
                                    SetUnitState(caster,UNIT_STATE_MANA,curMP)
                                end)
                            end
                        end)
                    end
                    TimerStart(CreateTimer(), 0.02, false, function()
                        SetUnitState(caster,UNIT_STATE_MANA,curMP)
                    end)
                    if HERO[0].ReleaseA or HERO[0].ReleaseW or HERO[0].ReleaseS or HERO[0].ReleaseD then
                        TimerStart(CreateTimer(), 0.1, false, function()
                            --print("скольжение после мышей")
                            SetUnitAnimationByIndex(caster,IndexAnimationWalk)
                        end)
                    end
                end)
            end
        else
            local caster=GetTriggerUnit()
            TimerStart(CreateTimer(), 0.05, false, function()
                BlzStartUnitAbilityCooldown(caster,FourCC('dssd'),1)
            end)
        end
    end)
end

function RemoveAllItems(hero)
    local slot={}
    --print("удаляем предметы")
    for i=0,5 do
        --print(i)
        slot[i]=GetItemTypeId(UnitItemInSlot(hero,i))
        --print(GetItemName(slot[i]))
        RemoveItem(UnitItemInSlot(hero,i))

    end
    return slot
end

function AddAlItems(hero,slot,maxHP,curHP)
    TimerStart(CreateTimer(), 0.05, false, function()
        for i=0,5 do
            UnitAddItemById(hero,slot[i])
        end
    end)
    --print(maxHP)
    TimerStart(CreateTimer(), 0.05, false, function()
        BlzSetUnitMaxHP(hero,maxHP)
        SetUnitState(hero,UNIT_STATE_LIFE,curHP)
    end)
end