---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitBB()
    end)
end

function InitBB()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if GetSpellAbilityId() == FourCC('dssd') then --мыши
            local caster=GetTriggerUnit()
           -- UnitAddItemById(caster,FourCC("I004"))
            TimerStart(CreateTimer(), 1/64, true, function()
                if GetUnitTypeId(caster)==FourCC('Hpal') then
                    DestroyTimer(GetExpiredTimer())
                    if HERO[0].ReleaseA or HERO[0].ReleaseW or HERO[0].ReleaseS or HERO[0].ReleaseD then
                       -- print("скольжение после мышей") --не работает
                        SetUnitAnimationByIndex(caster,IndexAnimationWalk)
                    end
                end
            end)
        end
    end)
end

