---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.11.2020 17:14
---
---
---
do
    TimerStart(CreateTimer(), 240, false, function()
        InitCry()
    end)
end
function InitCry()
    local gg_trg_RANGE = CreateTrigger()
    --print("initcry")
    TriggerRegisterUnitInRangeSimple(gg_trg_RANGE, 150, mainHero)
    TriggerAddAction(gg_trg_RANGE, function()
        local unit=GetTriggerUnit()
        --print("событие приближения")
        if GetUnitTypeId(unit)==FourCC("nvlw") and UnitAlive(unit) then
            --print(" подошел к девочке")
            normal_sound("war3mapImported\\Cry.wav",GetUnitXY(unit))
            --PlaySoundBJ(gg_snd_Cry)
            --print(GetUnitName())
           -- DisableTrigger(GetTriggeringTrigger())
            --StartPEONAI(boss)
        end

    end)
end




