---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitDA()
    end)
end

function InitDA()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if GetSpellAbilityId() == FourCC('A00M') then --армия тьмы
            local caster=GetTriggerUnit()
            CreateZobiesInArea(caster)
        end
    end)
end

function CreateZobiesInArea(hero)
    local x,y=GetUnitXY(hero)
    local e=nil
    GroupEnumUnitsInRange(perebor,x,y,1000,nil)
    while true do
        e = FirstOfGroup(perebor)

        if e == nil then break end
        if UnitAlive(e) and IsUnitVisible(e,Player(0)) and IsUnitEnemy(e,Player(0)) then
            local new=CreateUnit(GetOwningPlayer(hero),FourCC("n009"),GetUnitX(e),GetUnitY(e),GetRandomInt(0,360))
            Agr2Units(new,e)
            UnitApplyTimedLife(new,FourCC('BTLF'),10)
        end
        GroupRemoveUnit(perebor,e)
    end
end

function Agr2Units(u1,u2)
    IssueTargetOrder(u1,"attack",u2)
    IssueTargetOrder(u2,"attack",u1)
end