---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.11.2020 18:19
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        StartFearArea()
    end)

end
function StartFearArea()
    TimerStart(CreateTimer(), 2, true, function()
        local x,y=GetUnitXY(mainHero)
        local e=nil
        GroupEnumUnitsInRange(perebor,x,y,500,nil)
        while true do
            e = FirstOfGroup(perebor)
            if e == nil then break end
            if UnitAlive(e) and GetUnitTypeId(mainHero)==FourCC("Hpal") and (IsUnitEnemy(e,GetOwningPlayer(mainHero)) or GetOwningPlayer(e)==Player(PLAYER_NEUTRAL_PASSIVE)) and not IsUnitType(e,UNIT_TYPE_STRUCTURE) then
                if GetUnitTypeId(e)==FourCC("n006") then
                    if OrderId2String(GetUnitCurrentOrder(mainHero))~="move" then
                        --print("в страхе убегает")
                        local angle=-180+AngleBetweenXY(GetUnitX(e),GetUnitY(e),GetUnitXY(mainHero))/bj_DEGTORAD
                        local nx,ny=MoveXY(GetUnitX(e),GetUnitY(e),400,angle)
                        IssuePointOrder(e,"move",nx,ny)
                        local r=GetRandomInt(1,3)
                        --U01Peasant15A
                        --U01Peasant15B
                        --U01Peasant15С
                        local tl = Location(GetUnitXY(e))
                        if r==1 then
                            PlaySoundAtPointBJ(gg_snd_U01Peasant15A, 100, tl, 0)
                        elseif r==2 then
                            PlaySoundAtPointBJ(gg_snd_U01Peasant15B, 100, tl, 0)
                        elseif r==3 then
                            PlaySoundAtPointBJ(gg_snd_U01Peasant15C, 100, tl, 0)
                        end
                        RemoveLocation(tl)
                    end
                end
            end
            GroupRemoveUnit(perebor,e)
        end
    end)
end