---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitLightingSpell()
        InitDamageLighting()
    end)
end

function InitLightingSpell()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if GetSpellAbilityId() == FourCC('A00G') then --Удар молнией
            local caster=GetTriggerUnit()
            local target=GetSpellTargetUnit()
            local e=nil
            local k=1
            local ss=0
            GroupEnumUnitsInRange(perebor,GetUnitX(target),GetUnitY(target),300,nil)
            while true do
                e = FirstOfGroup(perebor)
                if e == nil then break end
                if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(caster)) and not IsUnitType(e,UNIT_TYPE_STRUCTURE)  and k<=4 then
                    k=k+1
                    UnitDamageTarget( caster, e, 1, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_UNIVERSAL, WEAPON_TYPE_WHOKNOWS )
                end
                GroupRemoveUnit(perebor,e)
            end
            PlaySoundNearUnit(caster,gg_snd_LightningBolt)
            local effect=AddSpecialEffect("Abilities\\Spells\\Other\\Monsoon\\MonsoonBoltTarget.mdl",GetUnitXY(caster))
            HERO[0].isLighting=true
            if k==1 then
                HERO[0].isLighting=false
            end
            TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
                if not HERO[0].isLighting then
                    DestroyTimer(GetExpiredTimer())
                end
                ss=ss+TIMER_PERIOD
                if ss>=GetSoundDuration(gg_snd_LightningBolt)//1000 then
                    ss=0
                    normal_sound("Abilities/Spells/Orc/LightningBolt/LightningBolt.flac",GetUnitXY(target))
                    --effect=AddSpecialEffect("Abilities\\Spells\\Other\\Monsoon\\MonsoonBoltTarget.mdl",GetUnitXY(caster))
                end
            end)
        end
    end)
end


function InitDamageLighting()
    local DamageTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        --TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
        TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
    end

    TriggerAddAction(DamageTrigger, function()
        local damage     = GetEventDamage() -- число урона
        if damage < 1 then return end
        local eventId         = GetHandleId(GetTriggerEventId())
        --local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
        local isEventDamaged = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)
        local target          = GetTriggerUnit() -- тот кто получил урон
        local caster          = GetEventDamageSource() -- тот кто нанёс урон


        if isEventDamaged then
            --print(GetUnitName(caster).." Бьёт "..GetUnitName(target))
            local damagetype = BlzGetEventDamageType()
            --print(ConvertDamageTypeToString(damagetype))
            local xLast=GetUnitX(caster)
            if damagetype==DAMAGE_TYPE_UNIVERSAL then
                local sec=0
                local ss=0
                local breakDamage=0
                TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
                    --print("Поражение болнией")
                    CreateLighting2Unit(caster,target)
                    if UnitDamageTarget( caster, target, 1, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS ) then
                        breakDamage=breakDamage+1
                        sec=sec+TIMER_PERIOD

                        if GetUnitLifePercent(target)<=5 then
                            SetUnitExploded(target, true)
                            --print("взрываем юнита")
                        end
                        if sec>=0.1 then

                            --print("звук геде")
                            sec=0
                            SetUnitState(caster,UNIT_STATE_MANA,GetUnitState(caster,UNIT_STATE_MANA)-2)
                        end
                       -- print(GetSoundDuration(gg_snd_LightningBolt)//1000)
                    end

                    StunUnit(target,1)
                    if not UnitAlive(target) then
                        DestroyTimer(GetExpiredTimer())
                        HERO[0].isLighting=false
                    end
                    if xLast~=GetUnitX(caster) or GetUnitState(caster,UNIT_STATE_MANA)<=1  then
                        --print("сдвинулся или потерял ману")
                        DestroyTimer(GetExpiredTimer())
                        HERO[0].isLighting=false
                    end

                    --Блок для боссов
                    if  breakDamage>=100 and target==BOSS then
                        --print("Босс сбрасывает с себя молнию")
                        local angle=360/12 -- 30
                        for i=1,12 do
                            local nx,ny=MoveXY(GetUnitX(target),GetUnitY(target),50,angle*i)
                            SpireCast(target,nx,ny)
                        end
                        DestroyTimer(GetExpiredTimer())
                        HERO[0].isLighting=false
                    end

                    xLast=GetUnitX(caster)
                end)

            end
        end

    end)
end

function CreateLighting2Unit(caster,target,id)
    if not id then id="CLPB" end
    local h=100
    local x,y=GetUnitXY(caster)
    local x1,y1=GetUnitXY(target)
    local z,z1=BlzGetUnitZ(caster)+h,BlzGetUnitZ(target)+h
    local l=AddLightningEx(id,true,x,y,z,x1,y1,z1) -- CLPB -- AFOD
    TimerStart(CreateTimer(), 1, false, function()
        DestroyLightning(l)
    end)
    --
end