---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitLightingSpell()
        InitDamageLighting()
    end)
end

function InitLightingSpell()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if GetSpellAbilityId() == FourCC('A00G') then --Удар молнией
            local caster=GetTriggerUnit()
            local target=GetSpellTargetUnit()
            local effect=AddSpecialEffect("Abilities\\Spells\\Other\\Monsoon\\MonsoonBoltTarget.mdl",GetUnitXY(caster))
        end
    end)
end


function InitDamageLighting()
    local DamageTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        --TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
        TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
    end

    TriggerAddAction(DamageTrigger, function()
        local damage     = GetEventDamage() -- число урона
        if damage < 1 then return end
        local eventId         = GetHandleId(GetTriggerEventId())
        --local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
        local isEventDamaged = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)
        local target          = GetTriggerUnit() -- тот кто получил урон
        local caster          = GetEventDamageSource() -- тот кто нанёс урон


        if isEventDamaged then
            --print(GetUnitName(caster).." Бьёт "..GetUnitName(target))
            local damagetype = BlzGetEventDamageType()
            --print(ConvertDamageTypeToString(damagetype))
            local xLast=GetUnitX(caster)
            if damagetype==DAMAGE_TYPE_LIGHTNING then
                local sec=0
                TimerStart(CreateTimer(), 0.1, true, function()
                    --print("Поражение болнией")
                    CreateLighting2Unit(caster,target)
                    if UnitDamageTarget( caster, target, 1, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS ) then
                        sec=sec+0.1
                        if sec>=1 then
                            sec=0
                            SetUnitState(caster,UNIT_STATE_MANA,GetUnitState(caster,UNIT_STATE_MANA)-1)
                        end
                    end
                    StunUnit(target,1)
                    if not UnitAlive(target) then
                        DestroyTimer(GetExpiredTimer())
                    end
                    if xLast~=GetUnitX(caster) or GetUnitState(caster,UNIT_STATE_MANA)<=1 then
                        --print("сдвинулся или потерял ману")
                        DestroyTimer(GetExpiredTimer())
                    end
                    xLast=GetUnitX(caster)
                end)

            end
        end

    end)
end

function CreateLighting2Unit(caster,target)
    local h=140
    local x,y=GetUnitXY(caster)
    local x1,y1=GetUnitXY(target)
    local z,z1=BlzGetUnitZ(caster)+h,BlzGetUnitZ(target)+h
    local l=AddLightningEx("CLPB",true,x,y,z,x1,y1,z1) -- CLPB
    TimerStart(CreateTimer(), 1, false, function()
        DestroyLightning(l)
    end)
    --
end