---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitCastMC()
    end)
end
tempHero=nil
function InitCastMC()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if GetSpellAbilityId() == FourCC('A005') then --Подчинение разума
            local caster=GetTriggerUnit()
            local target=GetSpellTargetUnit()
            --print("подчиняем разум "..GetUnitName(target))
            TimerStart(CreateTimer(), 1, false, function()
                UnitAddAbility(caster,FourCC("A003"))
                UnitAddAbility(caster,FourCC("A004"))
                UnitAddAbility(target,FourCC("A006")) -- освобождение разума
                UnitAddAbility(target,FourCC("Abun")) -- запрет дефолт атаки
                HERO[0].ReleaseW=false
                HERO[0].ReleaseA=false
                HERO[0].ReleaseS=false
                HERO[0].ReleaseD=false
                mainHero=target
                udg_mainHero=target
                tempHero=caster
                ResetUnitAnimation(tempHero)
                SelectUnitForPlayerSingle(mainHero,Player(0))
                SetUnitOwner(target,Player(0),true)
                TimerStart(CreateTimer(), 1, true, function()
                    if not UnitAlive(target) then
                        DestroyTimer(GetExpiredTimer())
                        --HERO[0].ReleaseW=false
                        --HERO[0].ReleaseA=false
                        --HERO[0].ReleaseS=false
                        --HERO[0].ReleaseD=false
                        mainHero=caster
                        udg_mainHero=caster
                        UnitRemoveAbility(caster,FourCC("A003"))
                        UnitRemoveAbility(caster,FourCC("A004"))
                        SelectUnitForPlayerSingle(mainHero,Player(0))
                    end
                end)
            end)
            --SelectUnitForPlayerSingle()
        end
        if GetSpellAbilityId() == FourCC('A006') then --Подчинение разума
            local caster=GetTriggerUnit()
            local amount=GetUnitState(caster,UNIT_STATE_LIFE)
            SetUnitExploded(caster,true)
            KillUnit(caster)
            HealUnit(tempHero,amount)
        end

    end)

end