---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.10.2020 16:32
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitNotAttack()
    end)
end
function InitNotAttack()
    local ThisClick = CreateTrigger()
    TriggerRegisterCommandEvent(ThisClick, FourCC("A002"), "darkritual")
    TriggerRegisterCommandEvent(ThisClick, FourCC("A005"), "acidbomb")
    TriggerRegisterCommandEvent(ThisClick, FourCC("A007"), "nagabuild")
    TriggerRegisterCommandEvent(ThisClick, FourCC("A00G"), "chainlightning")

    --TriggerRegisterCommandEvent(ThisClick, 0, "cancel")
    --TriggerRegisterCommandEvent(ThisClick, 0, "stop")
    TriggerAddAction(ThisClick, function()
        HERO[0].ONTarget=true
        --print("Способность на стадии активации")
    end)
    local TrigPressAny = CreateTrigger()
    TriggerRegisterPlayerEvent(TrigPressAny, Player(0), EVENT_PLAYER_MOUSE_DOWN)
    TriggerAddAction(TrigPressAny, function()
        if HERO[0].ONTarget then
            --print("Способность отменена или подтверждена")
            TimerStart(CreateTimer(), 0.1, false, function()
                HERO[0].ONTarget=false
                ForceUICancelBJ(Player(0))
            end)
        end
    end)
end