---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 19:30
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitSpire()
    end)
end

function InitSpire()
    local SpellTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerUnitEvent(SpellTrigger, player, EVENT_PLAYER_UNIT_SPELL_CAST)
    end
    TriggerAddAction(SpellTrigger, function()
        if GetSpellAbilityId() == FourCC('A007') then --Копьё
            local caster=GetTriggerUnit()
            local x,y=GetSpellTargetX(),GetSpellTargetY()
            SpireCast(caster,x,y)
        end
    end)
end

function SpireCast(caster,x,y)
    local xs,ys=GetUnitXY(caster)
    local angle=AngleBetweenXY(xs,ys,x,y)/bj_DEGTORAD
    local eff=AddSpecialEffect("Abilities\\Spells\\Orc\\Shockwave\\ShockwaveMissile.mdl",xs,ys)
    local dist=600
    local speed=15
    local curDist=0
    BlzSetSpecialEffectYaw(eff, math.rad(angle))

    TimerStart(CreateTimer(), 1/64, true, function()
        curDist=curDist+speed
        local nx,ny=MoveXY(xs,ys,curDist,angle)
        BlzSetSpecialEffectPosition(eff,nx,ny,GetTerrainZ(nx,ny)+60)
        BlzSetSpecialEffectColor(eff,255,0,0)
        local e=nil
        GroupEnumUnitsInRange(perebor,nx,ny,70,nil)
        while true do
            e = FirstOfGroup(perebor)
            if e == nil then break end
            if UnitAlive(e) and UnitAlive(caster) and (IsUnitEnemy(e,GetOwningPlayer(caster)) or GetOwningPlayer(e)==Player(PLAYER_NEUTRAL_PASSIVE)) and GetUnitTypeId(e)~=FourCC("hrif") then
                if GetUnitTypeId(e)==FourCC("osp1") then
                    KillUnit(e)
                end
                local nxe,nye=MoveXY(GetUnitX(e),GetUnitY(e),speed,angle)
                if not PointContentDestructable (nx,ny,70) then
                    --SetUnitX(e,nxe)
                    --SetUnitY(e,nye)
                    SetUnitPositionSmooth(e,nxe,nye)
                end
                --UnitDamageTarget( caster, e, 100, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
            end
            GroupRemoveUnit(perebor,e)
        end


        if curDist>=dist  then
            DestroyEffect(eff)
            DestroyTimer(GetExpiredTimer())
            UnitDamageArea(caster,10,nx,ny,70)
        end

        if PointContentDestructable (nx,ny,70,nil,nil,1) then
            DestroyEffect(eff)
            DestroyTimer(GetExpiredTimer())
            UnitDamageArea(caster,10,nx,ny,70)
            StunArea(caster,100,2,nx,ny)
        end
    end)
end