---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.10.2020 16:32
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitStunPerDie()
    end)
end
function InitStunPerDie()
    local DamageTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
    end
    TriggerAddAction(DamageTrigger, function()

        local damage     = GetEventDamage() -- число урона
        if damage < 1 then return end
        local eventId         = GetHandleId(GetTriggerEventId())
        local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
        local target          = GetTriggerUnit() -- тот кто получил урон
        local caster          = GetEventDamageSource() -- тот кто нанёс урон


        if isEventDamaging then
            TimerStart(CreateTimer(), 0.11, false, function()
                if UnitAlive(target) and GetUnitStatePercent(target,UNIT_STATE_LIFE,UNIT_STATE_MAX_LIFE)<=30 and GetOwningPlayer(target)~=Player(0) and GetUnitLevel(target)<=5 and not IsUnitType(target,UNIT_TYPE_UNDEAD) then
                    StunUnit(target,5)
                    UnitAddType(target,UNIT_TYPE_UNDEAD)
                    SetUnitOwner(target,Player(PLAYER_NEUTRAL_PASSIVE),true)
                   -- print("юнита можно съесть?")
                end
            end)
        end
    end)

end