---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.11.2020 15:13
---

do
    TimerStart(CreateTimer(), 3, false, function()
        InitGuardSystem()
    end)
end
function InitGuardSystem()
    local _,k,units=FindUnitOfType(FourCC("h00F"))
    --print("Найденно "..k.." стражников")
    for i=1,k do
        AddMarkAndRegister(units[i])
    end
end

function AddMarkAndRegister(unit)
    local radius=350
    local img=CreateImage("circ",radius,radius,radius,4000,4000,0,0,0,0,4)
    SetImageColor(img,255,0,0,200)
    SetImageRenderAlways(img, true)
    ShowImage(img,false)
    TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
        --local x,y=GetUnitXY(unit)
        if IsUnitVisible(unit,Player(0)) and GetUnitTypeId(mainHero)==FourCC("h00G") then
            local xs,ys=GetUnitX(unit)-radius/2-16,GetUnitY(unit)-radius/2-16
            --SetImagePosition(CircleImage,xs,ys,0)
            SetImagePosition(img,xs,ys,0)
            ShowImage(img,true)
        else
            ShowImage(img,false)
        end
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
            ShowImage(img,false)
        end
    end)


    --
    local this=CreateTrigger()
    TriggerRegisterUnitInRangeSimple(this, 150, unit)
    TriggerAddAction(this, function()
        local hero=GetTriggerUnit()
        if hero==mainHero and  GetUnitTypeId(mainHero)==FourCC("h00G") then
            local p=Player(0)
            SetPlayerAllianceStateBJ(p, GetOwningPlayer(unit), bj_ALLIANCE_UNALLIED)
            SetPlayerAllianceStateBJ(GetOwningPlayer(unit),p, bj_ALLIANCE_UNALLIED)
            local effAlarm=AddSpecialEffectTarget("Abilities\\Spells\\Other\\TalkToMe\\TalkToMe.mdl",unit,"overhead")
            TimerStart(CreateTimer(), 2, false, function()
                DestroyEffect(effAlarm)
            end)
        end
    end)
end

