---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.10.2020 0:13
do
    WLD={ --Белый лист из дестрактаблей
        [1]=FourCC('YTfc'),
        [2]=FourCC('YTLb'),
        [3]=FourCC('YtLc'),
        [4]=FourCC('YTac'),
        [5]=FourCC('YTpc'),
        [6]=FourCC('YTab'),
        [7]=FourCC('YTfb'),
        [8]=FourCC('YTpb'),

    }
end

do
    TimerStart(CreateTimer(), .1, false, function()
        InitMouseMoveTrigger()
        PlayUnitAnimationFromChat()
        --InitWASD(hero) --переместить в первый выбор героя
    end)

end

TIMER_PERIOD=1/64
HERO={}
function InitHeroTable(hero)
    perebor=CreateGroup()
    HERO[0]={
        UnitHero=hero,
        ReleaseW=false,
        ReleaseS=false,
        ReleaseD=false,
        ReleaseA=false,
        ReleaseLMB=false,
        ReleaseRMB=false,
        isAttacking=false,
        isCharging=false,
        isMoving=false,
        DropInventory=true,
        isShield=false,
        ShieldEff=nil,
    }
end


function InitWASD(hero)
    --print("initwasdSTART")
    InitHeroTable(hero)
    CreateWASDActions()
    BlockMouse()
    EnableDragSelect(false, false)
    BlzEnableSelections(false, false)
    local data=HERO[0]
    local angle=0

    local speed=5
    local animWalk=0
--[[
    print("testanim")
    local index=0
    TimerStart(CreateTimer(),2, true, function()
        SetUnitAnimationByIndex(hero,index)
        print(index)
        index=index+1
    end)]]
    animStand=0
    TimerStart(CreateTimer(),TIMER_PERIOD, true, function()
        data.UnitHero=mainHero -- костыль для смены героя
        hero=mainHero -- костыль для смены героя
        animWalk=animWalk+TIMER_PERIOD
        if animWalk>=0.933 then --длительность анимации WALK
            --print(animWalk)
            animWalk=0
        end
        if GetUnitTypeId(mainHero)==FourCC("H000") then -- начальный герой
            IndexAnimationWalk=1
            IndexAnimationAttack=5
            IndexAnimationCharge=6

        end
        if GetUnitTypeId(mainHero)==FourCC("Hpal") then   -- для вампира
            IndexAnimationWalk=0
            IndexAnimationAttack=GetRandomInt(12,13)
            --IndexAnimationCharge=16

        end
        if GetUnitTypeId(mainHero)==FourCC("n003") then   -- крыса квест
            IndexAnimationWalk=1
            IndexAnimationAttack=2

        end
        if GetUnitTypeId(mainHero)==FourCC("nrat") then   -- крыса обычная
            IndexAnimationWalk=1
            IndexAnimationAttack=2

        end
        if GetUnitTypeId(mainHero)==FourCC("h002") then   -- Расхититель гробниц
            IndexAnimationWalk=2
            IndexAnimationAttack=5
        end
        if GetUnitTypeId(mainHero)==FourCC("hfoo") then   -- бандит
            IndexAnimationWalk=5
            IndexAnimationAttack=GetRandomInt(3,4)

        end
        if GetUnitTypeId(mainHero)==FourCC("Edmm") then   -- Летучие мыши 2,5 dssd
            IndexAnimationWalk=1
            --IndexAnimationAttack=GetRandomInt(3,4)

        end
        if GetUnitTypeId(mainHero)==FourCC("h006") then   -- бандит 6 уровня
            IndexAnimationWalk=5
            IndexAnimationAttack=GetRandomInt(3,4)

        end
        if GetUnitTypeId(mainHero)==FourCC("h007") then   -- бандит стрелок
            IndexAnimationWalk=4
            IndexAnimationAttack=9

        end
        if GetUnitTypeId(mainHero)==FourCC("h00A") then   -- ассасин уровень 7
            IndexAnimationWalk=4
            IndexAnimationAttack=3

        end
        if GetUnitTypeId(mainHero)==FourCC("h00B") then   -- бандит уровень 8
            IndexAnimationWalk=5
            IndexAnimationAttack=GetRandomInt(3,4)

        end
        if GetUnitTypeId(mainHero)==FourCC("n006") then   -- мужик
            IndexAnimationWalk=6
            IndexAnimationAttack=GetRandomInt(4,5)

        end
        if GetUnitTypeId(mainHero)==FourCC("nvlw") then   -- девушка
            IndexAnimationWalk=1
            IndexAnimationAttack=3

        end
        if GetUnitTypeId(mainHero)==FourCC("o004") then   -- пеон
            IndexAnimationWalk=1
            IndexAnimationAttack=2
        end
        if GetUnitTypeId(mainHero)==FourCC("n00E") then   -- волк
            IndexAnimationWalk=2
            IndexAnimationAttack=4
        end

        --Автоподбор предметов
        if data.DropInventory and IsUnitType(mainHero,UNIT_TYPE_HERO) then
            local range=150
            local x,y=GetUnitXY(hero)
            SetRect(GlobalRect, x - range, y - range, x + range, y +range)
            EnumItemsInRect(GlobalRect,nil,function()
                UnitAddItem(hero,GetEnumItem())
                if GetItemType(GetEnumItem()) == ITEM_TYPE_POWERUP then
                    SetItemPosition(GetEnumItem(),-7000,-3000) --костыль которые чинить двойное срабатывание
                    RemoveItem(GetEnumItem())
                end
            end)
        end

        data.IsMoving=false
        if data.ReleaseW and data.ReleaseD == false and data.ReleaseA == false then
            --print("only w")
            angle = 90
            data.IsMoving = true
        end
        if data.ReleaseW and data.ReleaseD then
            --print("w+d")
            angle = 90 - 45
            data.IsMoving = true
        end
        if data.ReleaseW and data.ReleaseA then
            --print("w+s")
            angle = 90 + 45
            data.IsMoving = true
        end

        if data.ReleaseS and data.ReleaseD == false and data.ReleaseA == false then
            angle = 270
            data.IsMoving = true
        end
        if data.ReleaseS and data.ReleaseD then
            angle = 270 + 45
            data.IsMoving = true
        end
        if data.ReleaseS and data.ReleaseA then
            angle = 270 - 45
            data.IsMoving = true
        end

        if data.ReleaseD and data.ReleaseW == false and data.ReleaseS == false then
            angle = 0
            data.IsMoving = true
        end

        if data.ReleaseA and data.ReleaseW == false and data.ReleaseS == false then
            angle = 180
            data.IsMoving = true
        end

        if not UnitAlive(hero) then
            data.ReleaseW=false
            data.ReleaseA=false
            data.ReleaseS=false
            data.ReleaseD=false
        end
        if not StunSystem[GetHandleId(mainHero)] then
            StunUnit(mainHero,0.2)
        end
        if  StunSystem[GetHandleId(mainHero)].Time==0 then
            if not data.isAttacking and UnitAlive(hero) and not data.isShield then
                if data.IsMoving then
                    if  GetUnitTypeId(hero)==FourCC("Edmm") then--летучие мыши более быстрые
                        speed=7
                    else
                        speed=5
                    end
                    local x,y=GetUnitXY(hero)
                    local nx,ny=MoveXY(x,y,speed,angle)
                    SetUnitFacing(hero, angle)
                    SetUnitPositionSmooth(hero,nx,ny)

                    if animWalk==0 then
                        if  GetUnitTypeId(hero)~=FourCC("Edmm") then
                            SetUnitAnimationByIndex(hero,IndexAnimationWalk)
                            local r={SoundStep1,SoundStep2,SoundStep3,SoundStep4}
                            PlaySoundNearUnit(hero,r[GetRandomInt(1,4)])
                        else
                            --  print("летучие мыши рестарт анимации движения")
                        end
                        --print("w")
                        animStand=3
                    end
                else
                    --if animWalk==0 then

                    animStand=animStand+TIMER_PERIOD
                    if animStand>=2 then --длительность анимации WALK
                        --print(animWalk)
                        if  GetUnitTypeId(hero)~=FourCC("Edmm") then
                            ResetUnitAnimation(hero)
                            --print("дефолтный сборс")
                        else
                            -- print("сборс анимации мышей")
                        end
                        animStand=0
                    end
                    --end
                    --print("r")--..GetUnitName(mainHero)
                end
            else
                --print("onattaking")
            end
        else-- иначе юнит оглушен
            SetUnitAnimationByIndex(mainHero,5)
            UnitRemoveAbility(mainHero,FourCC("A003"))
            UnitRemoveAbility(mainHero,FourCC("A004"))
        end


    end)
end

function CreateWASDActions()
    -----------------------------------------------------------------OSKEY_W
    local gg_trg_EventUpW = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpW, Player(i), OSKEY_W, 0, true)
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpW, Player(i), OSKEY_UP, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpW, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseW and not data.isAttacking  and  UnitAlive(data.UnitHero) then
            data.ReleaseW = true
            SelectUnitForPlayerSingle(mainHero,Player(0))
            if not data.isAttacking and not data.isShield and StunSystem[GetHandleId(mainHero)].Time==0 then

                UnitAddForceSimple(data.UnitHero,90,5, 15)
                animStand=3
                SetUnitAnimationByIndex(data.UnitHero,IndexAnimationWalk)
            end

        end
    end)
    local TrigDepressW = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressW, Player(i), OSKEY_W, 0, false)
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressW, Player(i), OSKEY_UP, 0, false)
    end
    TriggerAddAction(TrigDepressW, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseW = false
    end)
    -----------------------------------------------------------------OSKEY_S
    local gg_trg_EventUpS = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpS, Player(i), OSKEY_S, 0, true)
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpS, Player(i), OSKEY_DOWN, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpS, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseS and not data.isAttacking and UnitAlive(data.UnitHero) then
            data.ReleaseS = true
            SelectUnitForPlayerSingle(mainHero,Player(0))
            if not data.isAttacking and not data.isShield and StunSystem[GetHandleId(mainHero)].Time==0 then
                animStand=3
                UnitAddForceSimple(data.UnitHero,270,5, 15)
                SetUnitAnimationByIndex(data.UnitHero,IndexAnimationWalk)

            end
        end
    end)
    local TrigDepressS = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressS, Player(i), OSKEY_S, 0, false)
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressS, Player(i), OSKEY_DOWN, 0, false)
    end
    TriggerAddAction(TrigDepressS, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseS = false
    end)
    -----------------------------------------------------------------OSKEY_D
    local TrigPressD = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigPressD, Player(i), OSKEY_D, 0, true)
        BlzTriggerRegisterPlayerKeyEvent(TrigPressD, Player(i), OSKEY_RIGHT, 0, true)
    end
    TriggerAddAction(TrigPressD, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseD and not data.isAttacking  and UnitAlive(data.UnitHero) then
            data.ReleaseD = true
            SelectUnitForPlayerSingle(mainHero,Player(0))
            if not data.isAttacking and not data.isShield and StunSystem[GetHandleId(mainHero)].Time==0 then
                animStand=3
                UnitAddForceSimple(data.UnitHero,0,5, 15)
                SetUnitAnimationByIndex(data.UnitHero,IndexAnimationWalk)

            end
        end
    end)
    local TrigDePressD = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDePressD, Player(i), OSKEY_D, 0, false)
        BlzTriggerRegisterPlayerKeyEvent(TrigDePressD, Player(i), OSKEY_RIGHT, 0, false)
    end
    TriggerAddAction(TrigDePressD, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseD = false

    end)
    -----------------------------------------------------------------OSKEY_A
    local TrigPressA = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigPressA, Player(i), OSKEY_A, 0, true)
        BlzTriggerRegisterPlayerKeyEvent(TrigPressA, Player(i), OSKEY_LEFT, 0, true)
    end
    TriggerAddAction(TrigPressA, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseA and not data.isAttacking  and  UnitAlive(data.UnitHero) and StunSystem[GetHandleId(mainHero)].Time==0 then
            data.ReleaseA = true
            SelectUnitForPlayerSingle(mainHero,Player(0))
            if not data.isAttacking and not data.isShield then
                animStand=3
                UnitAddForceSimple(data.UnitHero,180,5, 15)
                SetUnitAnimationByIndex(data.UnitHero,IndexAnimationWalk)

            end
        end
    end)
    local TrigDePressA = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDePressA, Player(i), OSKEY_A, 0, false)
        BlzTriggerRegisterPlayerKeyEvent(TrigDePressA, Player(i), OSKEY_LEFT, 0, false)
    end
    TriggerAddAction(TrigDePressA, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseA = false
    end)
    -----------------------------------------------------------------LMB
    local TrigPressLMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigPressLMB, Player(i), EVENT_PLAYER_MOUSE_DOWN)
    end
    TriggerAddAction(TrigPressLMB, function()
        --print("any")
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
            --это леваый клик всё внутри LMB

            local pid = GetPlayerId(GetTriggerPlayer())

            GetPlayerMouseX[pid]=BlzGetTriggerPlayerMouseX()
            GetPlayerMouseY[pid]=BlzGetTriggerPlayerMouseY()

            local data = HERO[pid]
            if  UnitAlive(data.UnitHero) then
                if data.ReleaseRMB  then
                    --Charge(data)
                end
                attack(data)
            else
                --print("Герой мёртв")
            end
        end
    end)
    local TrigDePressLMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigDePressLMB, Player(i), EVENT_PLAYER_MOUSE_UP)
    end

    TriggerAddAction(TrigDePressLMB, function()
        --print("any")
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
            local pid = GetPlayerId(GetTriggerPlayer())
            local data = HERO[pid]
            data.ReleaseLMB = false
        end
    end)
    -----------------------------------------------------------------RMB
    local TrigPressRMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigPressRMB, Player(i), EVENT_PLAYER_MOUSE_DOWN)
    end
    TriggerAddAction(TrigPressRMB, function()
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
            -- это правая кнопка
            local pid = GetPlayerId(GetTriggerPlayer())

            GetPlayerMouseX[pid]=BlzGetTriggerPlayerMouseX()
            GetPlayerMouseY[pid]=BlzGetTriggerPlayerMouseY()

            local data = HERO[pid]
            --data.Shield=true

            if  UnitAlive(data.UnitHero)  then --and IsUnitType(data.UnitHero,UNIT_TYPE_HERO)
                if GetUnitTypeId(data.UnitHero)==FourCC('Hpal') and StunSystem[GetHandleId(mainHero)].Time==0 then -- not data.isAttacking  and -- убрал атаку у щита
                    data.isShield=true
                    UnitAddAbility(data.UnitHero,FourCC("A003"))
                    UnitAddAbility(data.UnitHero,FourCC("A004"))
                    --BlzUnitDisableAbility(mainHero,FourCC('dssd'),true,false)
                    data.ReleaseW=false
                    data.ReleaseA=false
                    data.ReleaseS=false
                    data.ReleaseD=false
                    ResetUnitAnimation(data.UnitHero)
                    --data.ShieldEff=AddSpecialEffectTarget("Abilities\\Spells\\Human\\ManaShield\\ManaShieldCaster",data.UnitHero,"origin")
                end

                if data.ReleaseLMB then
                   -- Charge(data)
                end
                if not data.ReleaseRMB then
                    data.ReleaseRMB = true
                    --Charge(data)
                end

            end
        end
    end)
    local TrigDePressRMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigDePressRMB, Player(i), EVENT_PLAYER_MOUSE_UP)
    end
    TriggerAddAction(TrigDePressRMB, function()
        --print("depress")
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
            local pid = GetPlayerId(GetTriggerPlayer())
            local data = HERO[pid]
            local hero = data.UnitHero
            data.ReleaseRMB = false

           -- print("мышка отпущена")






            if data.isShield then
                UnitRemoveAbility(data.UnitHero,FourCC("A003"))
                UnitRemoveAbility(data.UnitHero,FourCC("A004"))
                --BlzUnitDisableAbility(mainHero,FourCC('dssd'),false,false)
                --DestroyEffect(data.ShieldEff)
                --print("щит отключен")
                data.isShield=false
            end

            if UnitAlive(hero) then
                if data.ReleaseA or data.ReleaseW or data.ReleaseS or data.ReleaseD then
                    -- print("Скольжение2") --не работает
                    SetUnitAnimationByIndex(mainHero,IndexAnimationWalk)
                end
            end
        end
    end)
end
---MouseX,MouseY=0,0
function BlockMouse()
    local this=CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER)
    TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
    TriggerAddAction(this, function()
      --  MouseX,MouseY=GetPlayerMouseX
       --print(OrderId2String(GetUnitCurrentOrder(mainHero)))
        if OrderId2String(GetUnitCurrentOrder(mainHero))=="dropitem" then
            HERO[0].DropInventory=false
            TimerStart(CreateTimer(), 2, false, function()
                HERO[0].DropInventory=true
            end)
        end

        if OrderId2String(GetUnitCurrentOrder(mainHero))=="smart" or OrderId2String(GetUnitCurrentOrder(mainHero))=="move"  then --Строковый список приказов, которые игрок не может выполнить
            BlzPauseUnitEx(mainHero,true)
            BlzPauseUnitEx(mainHero,false)
        end
    end)
end
function attack(data)
    if not data.ReleaseLMB and  UnitAlive(data.UnitHero) and not IsUnitPaused(data.UnitHero) and not data.isShield then
        data.ReleaseLMB = true
        if not data.isAttacking  and not data.isCharging  and not data.ONTarget then
            --print("пытаемся атаковать, запускаем кд атаки и прерываем движение")
            --print("a "..GetUnitName(mainHero))
            data.isAttacking=true

            --local state={data.ReleaseW,data.ReleaseA,data.ReleaseS,data.ReleaseD}
            data.ReleaseW=false
            data.ReleaseA=false
            data.ReleaseS=false
            data.ReleaseD=false
            SetUnitAnimationByIndex(data.UnitHero,IndexAnimationAttack)
            local e=nil
            local k=0
            GroupEnumUnitsInRange(perebor,GetUnitX(mainHero),GetUnitY(mainHero),200,nil)

            while true do
                e = FirstOfGroup(perebor)
                if e == nil then break end
                if UnitAlive(e) and UnitAlive(mainHero) and (IsUnitEnemy(e,GetOwningPlayer(mainHero)) or GetOwningPlayer(e)==Player(PLAYER_NEUTRAL_PASSIVE)) then
                    k=k+1
                end
                GroupRemoveUnit(perebor,e)
            end
            if k>1 and GetUnitTypeId(mainHero)==FourCC("Hpal") then
                SetUnitAnimationByIndex(data.UnitHero,12)-- всегда сплешь
                local eff=AddSpecialEffectTarget("Sweep_Attachments_FX\\Sweep_Blood_Large",mainHero,"hand left")
                TimerStart(CreateTimer(), 5, false, function()
                    DestroyEffect(eff)
                end)
            end


            local angle=-180+AngleBetweenXY(GetPlayerMouseX[0],GetPlayerMouseY[0],GetUnitX(data.UnitHero),GetUnitY(data.UnitHero))/bj_DEGTORAD
            SetUnitFacing(data.UnitHero,angle)
            TimerStart(CreateTimer(), 0.5, false, function()
                local damage=BlzGetUnitBaseDamage(mainHero,0)
                if UnitHasItemOfTypeBJ(mainHero,FourCC('I005')) then
                    damage=damage+15
                end
                local nx,ny=MoveXY(GetUnitX(data.UnitHero),GetUnitY(data.UnitHero),100,GetUnitFacing(data.UnitHero))
                if GetUnitTypeId(mainHero)~=FourCC("Edmm") and not data.isShield then
                    local is,_,k=UnitDamageArea(data.UnitHero,damage,nx,ny,100)
                    if not is then
                        local tl = Location(GetUnitXY(mainHero))
                        local r=GetRandomInt(1,2)
                        if r==1 then
                            PlaySoundAtPointBJ(SoundAttack3, 100, tl, 0)
                        else
                            PlaySoundAtPointBJ(SoundAttack4, 100, tl, 0)
                        end
                        RemoveLocation(tl)
                    end

                end
            end)

            TimerStart(CreateTimer(), 0.7, false, function()
                data.isAttacking=false
                --data.ReleaseLMB = false
            end)
        end
    end
end


function dash(data) --ОТКЛЮЧЕНО, ЭТО ПЕРЕКАТ
    if not data.isDash and not data.isCharging then
        data.isDash=true
        local angle=-180+AngleBetweenXY(GetPlayerMouseX[0],GetPlayerMouseY[0],GetUnitXY(data.UnitHero))/bj_DEGTORAD
        UnitAddForceSimple(data.UnitHero,angle,10,200)
        SetUnitAnimationByIndex(data.UnitHero,6)
        TimerStart(CreateTimer(), 0.3, false, function()
            data.isDash=false
        end)
    end
end

function Charge(data) --Отключено за ненадобьюсть
    if not data.isCharging and GetUnitTypeId(data.UnitHero)==FourCC('Hpal') then --только вампир может в рывок
        data.isCharging=true
        local angle=-180+AngleBetweenXY(GetPlayerMouseX[0],GetPlayerMouseY[0],GetUnitXY(data.UnitHero))/bj_DEGTORAD
        UnitAddForceSimple(data.UnitHero,angle,20,300)
        SetUnitFacing(data.UnitHero,angle)
        SetUnitAnimationByIndex(data.UnitHero,IndexAnimationCharge)


        TimerStart(CreateTimer(), 0.15,false, function()
            if data.IsMoving then
                SetUnitAnimationByIndex(data.UnitHero,IndexAnimationWalk)
            else
               ResetUnitAnimation(data.UnitHero)
            end
            --print("Рывок перезаряжен")
           -- data.isCharging=false
        end)

        TimerStart(CreateTimer(), 2, false, function()
            --print("Рывок перезаряжен")
            data.isCharging=false
        end)
    end
end


onForces = {}
function UnitAddForceSimple(hero, angle, speed, distance,flag)
    -- псевдо вектор использовать только для юнитов
    local currentdistance = 0
    if onForces[GetHandleId(hero)] == nil then
        onForces[GetHandleId(hero)] = true
    end
    if not IsUnitType(hero, UNIT_TYPE_STRUCTURE) and onForces[GetHandleId(hero)]  then
        onForces[GetHandleId(hero)]=false
        local m=0
        TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
            currentdistance = currentdistance + speed
            --print(currentdistance)
            local x, y = GetUnitX(hero), GetUnitY(hero)
            local newX, newY = MoveX(x, speed, angle), MoveY(y, speed, angle)
            SetUnitPositionSmooth(hero, newX, newY)
            if flag==5 then
                UnitDamageArea(hero,5,newX, newY,100)
                m=m+1
                if m>=6 then
                    local eff=AddSpecialEffect("Blood Massacre",newX, newY)
                    BlzSetSpecialEffectColor(eff,255,0,0,0)
                    DestroyEffect(eff)
                    m=0
                end
            end
            if flag==6 then
                local e=nil
                GroupEnumUnitsInRange(perebor,newX, newY,100,nil)
                while true do
                    e = FirstOfGroup(perebor)
                    if e == nil then break end
                    if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(hero)) and not IsUnitType(e,UNIT_TYPE_STRUCTURE) and IsUnitType(e,UNIT_TYPE_HERO) then
                        --if StunSystem[GetHandleId(e)].Time==0 then
                        --    StunUnit(e,1)
                        --end
                        UnitAddForceSimple(e,GetUnitFacing(hero),15,200)
                    end
                    GroupRemoveUnit(perebor,e)
                end
            end

            if currentdistance >= distance then
                --or (data.OnWater and data.OnTorrent==false)
                --data.IsDisabled=false
                --data.OnWater=false
                if flag==5 then
                    ShowUnit(hero,true)

                end

                if flag==6 then -- башлорд конец бега
                    ResetUnitAnimation(hero)
                    BlzPauseUnitEx(hero,false)
                    SetUnitTimeScale(hero,1)
                end

                if IsUnitType(hero,UNIT_TYPE_HERO) then
                    if HERO[0].isCharging then
                        --print("рывок окончен")
                        --DestroyTimer(GetExpiredTimer())
                        --onForces[GetHandleId(hero)]=true
                        --HERO[0].isCharging=false
                        ResetUnitAnimation(hero)
                    end
                end
                DestroyTimer(GetExpiredTimer())
                onForces[GetHandleId(hero)]=true
                --print("stop cur="..currentdistance.." dist="..distance)
            end
        end)
    end
end

GetPlayerMouseX = {}
GetPlayerMouseY = {}
function InitMouseMoveTrigger()
    local MouseMoveTrigger = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        local player = Player(i)
        TriggerRegisterPlayerEvent(MouseMoveTrigger, player, EVENT_PLAYER_MOUSE_MOVE)
        GetPlayerMouseX[i] = 0
        GetPlayerMouseY[i] = 0
    end
    TriggerAddAction(MouseMoveTrigger, function()
        local id = GetPlayerId(GetTriggerPlayer())
        if BlzGetTriggerPlayerMouseX() ~= 0 then
            GetPlayerMouseX[id] = BlzGetTriggerPlayerMouseX()
            GetPlayerMouseY[id] = BlzGetTriggerPlayerMouseY()
        end
    end)
end

function UnitDamageArea(u,damage,x,y,range)
    local isdamage=false
    local e=nil
    local hero=nil
    GroupEnumUnitsInRange(perebor,x,y,range,nil)
    local k=0
    while true do
        e = FirstOfGroup(perebor)
        if e == nil then break end
        if UnitAlive(e) and UnitAlive(u) and (IsUnitEnemy(e,GetOwningPlayer(u)) or GetOwningPlayer(e)==Player(PLAYER_NEUTRAL_PASSIVE)) then
            UnitDamageTarget( u, e, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
            isdamage=true
            hero=e
            k=k+1
        end
        GroupRemoveUnit(perebor,e)
    end
    if PointContentDestructable(x,y,range,true,1+damage,u) then	isdamage=true	end
    return isdamage, hero,k
end

GlobalRect=Rect(0,0,0,0)
function PointContentDestructable (x,y,range,iskill,damage,flag)
    local content=false
    if range==nil then range=80 end
    if iskill==nil then iskill=false end
    local d=nil
    SetRect(GlobalRect, x - range, y - range, x + range, y +range)
    EnumDestructablesInRect(GlobalRect,nil,function ()
        d=GetEnumDestructable()
        if GetDestructableLife(d)>0 then
            content=true

            if  (GetDestructableTypeId(d)==FourCC("B005") or GetDestructableTypeId(d)==FourCC("OTip") ) and  flag==1 then -- блокиратор или платформа
                content=false
            end
            if iskill then
                if GetUnitTypeId(flag)==FourCC("Hpal") then
                    local tl = Location(GetUnitXY(flag))
                    local r=GetRandomInt(1,2)
                    if r==1 then
                        PlaySoundAtPointBJ(SoundAttack5, 100, tl, 0)
                    else
                        PlaySoundAtPointBJ(SoundAttack6, 100, tl, 0)
                    end
                    RemoveLocation(tl)
                end
                SetDestructableLife(d,GetDestructableLife(d)-damage)
                if GetDestructableLife(d)>=1 then
                    SetDestructableAnimation(d,"Stand Hit")
                end
                --KillDestructable(d)
            end
        end
    end)
    return content,d
end
CQX=430
CQY=6500
function PlayUnitAnimationFromChat()
    local this=CreateTrigger()
    TriggerRegisterPlayerChatEvent(this,Player(0),"",true)
    TriggerAddAction(this, function()
        local s=S2I(GetEventPlayerChatString())
        if GetEventPlayerChatString()=="w" then
            CreateForUnitWayToPoint(mainHero,CQX,CQY)
            return
        end
        if GetEventPlayerChatString()=="m" then
            UnitAddItemById(mainHero,FourCC("I00A"))
            --print("получена руна морфа, где форма мышей")
            return
        end
        if GetEventPlayerChatString()=="n" then
            UnitAddItemById(mainHero,FourCC("I00B"))
            return
        end

        SetUnitAnimationByIndex(mainHero,s)
        --print(GetUnitName(mainHero).." "..s)
    end)
end