---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.11.2020 16:12
---

do
    TimerStart(CreateTimer(), 1, false, function()
        InitPreloadStart()
    end)
end

function InitPreloadStart()
    --print("Start preload tester")
    --PreloadGenClear()
    Preloader("save\\BO.txt")
    local k=0
    local s=BlzGetAbilityTooltip (FourCC('Agyv'),  0)
    if #s>2 then
        print("First Game")
        s=1
        Preload("\")\ncall BlzSetAbilityTooltip ('Agyv',\""..s.."\",0)".."\n//")
        PreloadGenEnd("save\\BO.txt")
        PreloadGenClear()
    else
        Preload("\")\ncall BlzSetAbilityTooltip ('Agyv',\""..R2I(s+1).."\",0)".."\n//")
        PreloadGenEnd("save\\BO.txt")
        PreloadGenClear()
        print("Game № "..R2I(s+1))
    end
end