---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.11.2020 22:59
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        --звуки попаданий
        SoundAttack1 = CreateSound("Sound\\Units\\Combat\\MetalHeavySliceFlesh3", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack1, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack1, 853)
        SetSoundVolume(SoundAttack1, 250)
        SoundAttack2 = CreateSound("Sound\\Units\\Combat\\MetalHeavySliceFlesh2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack2, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack2, 853)
        SetSoundVolume(SoundAttack2, 250)
        --Звуки промахов
        SoundAttack3 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceFlesh2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack3, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack3, 853)
        SetSoundVolume(SoundAttack3, 250)
        SoundAttack4 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceFlesh2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack4, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack4, 853)
        SetSoundVolume(SoundAttack4, 250)
        --Звуки ударов по декору
        SoundAttack5 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceWood1", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack5, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack5, 853)
        SetSoundVolume(SoundAttack5, 250)
        SoundAttack6 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceWood2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack6, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack6, 853)
        SetSoundVolume(SoundAttack6, 250)
        HintSound = CreateSound("Sound\\Interface\\Hint", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(HintSound, "MetalHeavySliceFlesh")
        SetSoundDuration(HintSound, 853)
        SetSoundVolume(HintSound, 250)
        --Звуки шагов
        SoundStep1 = CreateSound("Sound\\Units\\Footsteps\\HeroStep1", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundStep1, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundStep1, 853)
        SetSoundVolume(SoundStep1, 250)
        SoundStep2 = CreateSound("Sound\\Units\\Footsteps\\HeroStep2", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(SoundStep2, "HeroCinematicStep2")
        SetSoundDuration(SoundStep2, 853)
        SetSoundVolume(SoundStep2, 250)
        SoundStep3 = CreateSound("Sound\\Units\\Footsteps\\HeroStep3", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(SoundStep3, "HeroCinematicStep2")
        SetSoundDuration(SoundStep3, 853)
        SetSoundVolume(SoundStep3, 250)
        SoundStep4 = CreateSound("Sound\\Units\\Footsteps\\HeroStep4", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(SoundStep4, "HeroCinematicStep2")
        SetSoundDuration(SoundStep4, 853)
        SetSoundVolume(SoundStep4, 250)
    end)
end

function PlaySoundNearUnit(hero,sound)
    local tl = Location(GetUnitXY(hero))
    PlaySoundAtPointBJ(sound, 100, tl, 0)
    RemoveLocation(tl)
    --print("звук хотьбы")
end