---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.11.2020 22:59
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        --звуки попаданий
        SoundAttack1 = CreateSound("Sound\\Units\\Combat\\MetalHeavySliceFlesh3", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack1, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack1, 600)
        SetSoundVolume(SoundAttack1, 250)
        SoundAttack2 = CreateSound("Sound\\Units\\Combat\\MetalHeavySliceFlesh2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack2, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack2, 600)
        SetSoundVolume(SoundAttack2, 250)
        --Звуки промахов
        SoundAttack3 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceFlesh2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack3, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack3, 853)
        SetSoundVolume(SoundAttack3, 250)
        SoundAttack4 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceFlesh2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack4, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack4, 853)
        SetSoundVolume(SoundAttack4, 250)
        --Звуки ударов по декору
        SoundAttack5 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceWood1", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack5, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack5, 853)
        SetSoundVolume(SoundAttack5, 250)
        SoundAttack6 = CreateSound("Sound\\Units\\Combat\\MetalLightSliceWood2", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack6, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack6, 853)
        SetSoundVolume(SoundAttack6, 250)
        HintSound = CreateSound("Sound\\Interface\\Hint", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(HintSound, "MetalHeavySliceFlesh")
        SetSoundDuration(HintSound, 853)
        SetSoundVolume(HintSound, 250)
        --Нейтральные удары
        SoundAttack7 = CreateSound("Sound\\Units\\Combat\\MetalLightChopFlesh1.flac", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack7, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack7, 853)
        SetSoundVolume(SoundAttack7, 250)
        SoundAttack8 = CreateSound("Sound\\Units\\Combat\\MetalLightChopFlesh2.flac", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundAttack8, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundAttack8, 853)
        SetSoundVolume(SoundAttack8, 250)

        --Звуки шагов
        SoundStep1 = CreateSound("Sound\\Units\\Footsteps\\HeroStep1", false, true, true, 0, 0, "MissilesEAX")
        SetSoundParamsFromLabel(SoundStep1, "MetalHeavySliceFlesh")
        SetSoundDuration(SoundStep1, 853)
        SetSoundVolume(SoundStep1, 250)
        SoundStep2 = CreateSound("Sound\\Units\\Footsteps\\HeroStep2", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(SoundStep2, "HeroCinematicStep2")
        SetSoundDuration(SoundStep2, 853)
        SetSoundVolume(SoundStep2, 250)
        SoundStep3 = CreateSound("Sound\\Units\\Footsteps\\HeroStep3", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(SoundStep3, "HeroCinematicStep2")
        SetSoundDuration(SoundStep3, 853)
        SetSoundVolume(SoundStep3, 250)
        SoundStep4 = CreateSound("Sound\\Units\\Footsteps\\HeroStep4", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(SoundStep4, "HeroCinematicStep2")
        SetSoundDuration(SoundStep4, 853)
        SetSoundVolume(SoundStep4, 250)
        --Эффекты
        --молния
        gg_snd_LightningBolt = CreateSound("Abilities/Spells/Orc/LightningBolt/LightningBolt.flac", false, true, true, 0, 0, "SpellsEAX")
        SetSoundParamsFromLabel(gg_snd_LightningBolt, "LightningBolt")
        SetSoundDuration(gg_snd_LightningBolt, 1999)
        SetSoundVolume(gg_snd_LightningBolt, 127)

    end)
end

function PlaySoundNearUnit(hero,sound)
    local tl = Location(GetUnitXY(hero))
    PlaySoundAtPointBJ(sound, 100, tl, 0)
    RemoveLocation(tl)
   -- print("звук молнии")
end

function normal_sound (s,x,y)
    local  snd = CreateSound(s, false, true, true, 10, 10, "CombatSoundsEAX")
    SetSoundChannel(snd, 40)
    SetSoundVolume(snd, 127)
    SetSoundPitch(snd, 1)
    SetSoundDistances(snd, 600, 10000)
    SetSoundDistanceCutoff(snd, 2100)
    SetSoundConeAngles(snd, 0.0, 0.0, 127)
    SetSoundConeOrientation(snd, 0.0, 0.0, 0.0)
    SetSoundPosition(snd, x, y, 50)
    StartSound(snd)
    KillSoundWhenDone(snd)
end

function PreloadSound3D_snd(s)
local  snd = CreateSound(s,false,true,true,10,10,"CombatSoundsEAX")
 SetSoundChannel(snd,5)
 SetSoundVolume(snd,127)
 SetSoundPitch(snd, 1)
 SetSoundDistances(snd,999999,99999)
 SetSoundDistanceCutoff(snd,99999)
 SetSoundConeAngles(snd,0.0,0.0,127)
 SetSoundConeOrientation(snd,0.0,0.0,0.0)
 SetSoundPosition(snd,0.0,0.0,50.0)
 StartSound(snd)
 StopSound(snd, false, false)

end