---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.10.2020 22:45
---
do
    TimerStart(CreateTimer(), 0.11, false, function()
        InitPUI()
    end)
end
secToHideItem=0
function InitPUI()

    local frame,text=CreateInfoItemBOX()
    local this = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddAction(this, function()
        local item=GetManipulatedItem()
        if GetItemTypeId(item)~=FourCC("I004") then --Список исключений предметов
            BlzFrameSetVisible(frame,true)
            BlzFrameSetTexture(frame,BlzGetItemIconPath(item),0,true)
            BlzFrameSetAlpha(frame,255)
            BlzFrameSetText(text, "You acquired new item:         |cffffcc00"..GetItemName(item).."|r")
            --|cffffcc001-й уровень:|r
            local p=1/64
            secToHideItem=secToHideItem+6
            TimerStart(CreateTimer(), p, true, function()
                secToHideItem=secToHideItem-p
                if secToHideItem<=0 then
                    DestroyTimer(GetExpiredTimer())
                    BlzFrameSetVisible(frame,false)
                end
                if secToHideItem<=2.5 then
                    BlzFrameSetAlpha(frame,R2I(secToHideItem*100))
                end
            end)
        end

    end)

end

function CreateInfoItemBOX()
    local x,y=0.45,0.15
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetTexture(buttonIconFrame, "texture", 0, true)
    BlzFrameSetSize(buttonIconFrame, 0.039/2, 0.039/2)
    BlzFrameSetAbsPoint(buttonIconFrame, FRAMEPOINT_LEFT, x, y)

    local textCurrent = BlzCreateFrameByType("TEXT", "ButtonChargesText", buttonIconFrame, "", 0)
    BlzFrameSetAbsPoint(textCurrent, FRAMEPOINT_LEFT,  x-0.21, y)
    BlzFrameSetScale(textCurrent,2)
    BlzFrameSetText(textCurrent, "You acquired new item:      ")
    BlzFrameSetVisible(buttonIconFrame,false)
    return buttonIconFrame,textCurrent
end